import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {build} from "esbuild";
import {pathToFileURL} from "node:url";
fs.mkdirSync(".sites-runtime/seller-tests",{recursive:true});
const aliases={"cloudflare:workers":"env.mjs","@/app/chatgpt-auth":"identity.mjs","./proxy-checker":"checker.mjs"};
await build({entryPoints:["lib/shop-service.ts"],outfile:".sites-runtime/seller-tests/service.mjs",bundle:true,platform:"node",format:"esm",plugins:[{name:"fixture-boundaries",setup(b){b.onResolve({filter:/.*/},a=>aliases[a.path]?{path:path.resolve("tests/fixtures",aliases[a.path])}:null);}}]});
await build({entryPoints:["lib/local-auth.ts","lib/money-input.ts"],outdir:".sites-runtime/seller-tests",bundle:true,platform:"node",format:"esm",outExtension:{".js":".mjs"}});
const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const name of fs.readdirSync("drizzle").filter(f=>f.endsWith(".sql")).sort())db.exec(fs.readFileSync("drizzle/"+name,"utf8"));
class Statement{constructor(query,args=[]){this.query=query;this.args=args;}bind(...args){return new Statement(this.query,args);}async first(){return db.prepare(this.query).get(...this.args)??null;}async all(){return {results:db.prepare(this.query).all(...this.args)};}async run(){return {meta:{changes:Number(db.prepare(this.query).run(...this.args).changes)}};}}
const database={prepare:q=>new Statement(q),batch:async statements=>{db.exec("BEGIN IMMEDIATE");try{const r=[];for(const s of statements)r.push(await s.run());db.exec("COMMIT");return r;}catch(e){db.exec("ROLLBACK");throw e;}}};
const key="a1".repeat(32),owner={userId:"owner",email:"owner@example.test",displayName:"Owner"};globalThis.__shopEnv={DB:database,PROXY_ENCRYPTION_KEY:key,ADMIN_EMAIL:owner.email};globalThis.__shopUser=owner;globalThis.__health={};
const originalFetch=fetch,originalNow=Date.now;let now=Date.now();Date.now=()=>now;globalThis.fetch=async()=>new Response(null,{status:204});
const {shopSnapshot,shopAction,maintenance}=await import(pathToFileURL(path.resolve(".sites-runtime/seller-tests/service.mjs")));
const {authAction,localIdentity}=await import(pathToFileURL(path.resolve(".sites-runtime/seller-tests/local-auth.mjs")));
const {moneyDraft,moneyValue,moneyDisplay}=await import(pathToFileURL(path.resolve(".sites-runtime/seller-tests/money-input.mjs")));
const req=cookie=>new Request("https://shop.test/api/shop",{method:"POST",headers:{origin:"https://shop.test","cf-connecting-ip":"192.0.2.10",...cookie?{cookie}:{} }});
let count=0;const passed=n=>{count++;console.log("PASS "+n);};
try{
 assert.equal(moneyDraft("0011000"),"11000");assert.equal(moneyDraft(""),"");assert.equal(moneyDisplay("11000"),"11.000");assert.equal(moneyValue("11.000"),11000);assert.equal(moneyValue(""),null);assert.equal(moneyDraft("-100"),null);passed("Price supports erase, strips leading zeroes, formats thousands and rejects negative text");
 await shopSnapshot();await assert.rejects(()=>authAction(database,key,owner.email,req(),{action:"register",email:owner.email,password:"fixture-password-123",name:"Pretend owner"}),/không thể/);
 const admin=await authAction(database,key,owner.email,req(),{action:"register",email:owner.email,password:"fixture-password-123",name:"Owner"},owner);assert.equal((await localIdentity(database,req(admin.cookie.split(";")[0]))).isAdmin,true);passed("Owner login linked only after verified existing owner; email alone cannot claim admin");
 const a=await authAction(database,key,owner.email,req(),{action:"register",email:"seller-a@example.test",password:"fixture-password-123",name:"Fixture Seller A",role:"ADMIN"});const b=await authAction(database,key,owner.email,req(),{action:"register",email:"seller-b@example.test",password:"fixture-password-123",name:"Fixture Seller B"});
 const ac=a.cookie.split(";")[0],bc=b.cookie.split(";")[0],actorA=await localIdentity(database,req(ac)),actorB=await localIdentity(database,req(bc));assert.equal(actorA.isAdmin,false);assert(a.cookie.includes("HttpOnly; Secure; SameSite=Lax"));assert(!JSON.stringify(db.prepare("SELECT * FROM auth_accounts").all()).includes("fixture-password"));assert(!JSON.stringify(db.prepare("SELECT * FROM auth_sessions").all()).includes(ac.split("=")[1]));passed("Registration ignores role injection; passwords and session tokens stored hashed");
 await assert.rejects(()=>authAction(database,key,owner.email,req(),{action:"login",email:"seller-a@example.test",password:"incorrect"}),/không đúng/);const login=await authAction(database,key,owner.email,req(),{action:"login",email:"SELLER-A@example.test",password:"fixture-password-123"});assert.equal((await localIdentity(database,req(login.cookie.split(";")[0]))).userId,actorA.userId);passed("Email login authenticates correct password; incorrect password rejected");
 await authAction(database,key,owner.email,req(login.cookie.split(";")[0]),{action:"logout"});assert.equal(await localIdentity(database,req(login.cookie.split(";")[0])),null);assert.equal((await localIdentity(database,req(ac))).userId,actorA.userId);passed("Logout revokes exactly that session");
 await assert.rejects(()=>authAction(database,key,owner.email,new Request("https://shop.test/api/auth",{method:"POST",headers:{origin:"https://evil.test"}}),{action:"logout"}),/khác nguồn/);passed("Auth mutations reject cross-origin requests");
 await assert.rejects(()=>shopAction(req(ac),{action:"sepay-settings",enabled:false}),/quản trị/);assert.equal((await shopSnapshot(req(ac))).user.isAdmin,false);passed("Local customer session overrides owner browser context without admin privilege");
 const inviteA=await shopAction(req(),{action:"seller-invite",email:actorA.email});await assert.rejects(()=>shopAction(req(bc),{action:"seller-accept",token:inviteA.invite}),/không đúng/);await shopAction(req(ac),{action:"seller-accept",token:inviteA.invite});await assert.rejects(()=>shopAction(req(ac),{action:"seller-accept",token:inviteA.invite}),/không còn/);const inviteB=await shopAction(req(),{action:"seller-invite",email:actorB.email});await shopAction(req(bc),{action:"seller-accept",token:inviteB.invite});passed("CTV invitation bound to email, single-use and admin-issued");
 await shopAction(req(ac),{action:"seller-save",code:"seller-key",name:"Fixture keys",kind:"KEY",price:11000,description:"Fixture",enabled:true});await shopAction(req(ac),{action:"seller-import",product:"seller-key",text:"fixture-key-one\nfixture-key-two"});assert.equal(db.prepare("SELECT enabled FROM products WHERE code='seller-key'").get().enabled,0);await assert.rejects(()=>shopAction(req(ac),{action:"seller-review",code:"seller-key",approve:true}),/quản trị/);await assert.rejects(()=>shopAction(req(bc),{action:"seller-import",product:"seller-key",text:"wrong"}),/của bạn/);assert.equal((await shopSnapshot(req(bc))).seller.products.length,0);passed("CTV cannot self-approve, edit/import another seller stock or view their draft");
 globalThis.__shopUser=null;assert(!(await shopSnapshot()).products.some(p=>p.code==="seller-key"));globalThis.__shopUser=owner;await shopAction(req(),{action:"seller-review",code:"seller-key",approve:true});passed("Pending product hidden publicly; admin approval opens sale");
 const buyer={userId:"buyer",email:"buyer@example.test",displayName:"Fixture Buyer"};globalThis.__shopUser=buyer;await shopSnapshot();const rid=crypto.randomUUID();await shopAction(req(),{action:"create-order",product:"seller-key",quantity:2,requestId:rid});const order=db.prepare("SELECT * FROM orders WHERE request_id=?").get(rid);assert.equal(order.unit_fee,550);assert.equal(order.seller_id,actorA.userId);assert.equal(db.prepare("SELECT COUNT(*) n FROM seller_sales").get().n,0);
 globalThis.__shopUser=owner;await shopAction(req(ac),{action:"seller-save",code:"seller-key",name:"Fixture keys",kind:"KEY",price:99000,description:"New price"});await shopAction(req(),{action:"approve",id:order.id});const sale=db.prepare("SELECT * FROM seller_sales WHERE order_id=?").get(order.id);assert.equal(sale.gross,22000);assert.equal(sale.fee,1100);assert.equal(sale.net,20900);await assert.rejects(()=>shopAction(req(),{action:"approve",id:order.id}),/trạng thái/);assert.equal(db.prepare("SELECT COUNT(*) n FROM seller_sales").get().n,1);passed("5% fee locked per item at order creation; recorded once only after successful delivery");
 assert.equal((await shopSnapshot(req(bc))).seller.sales.length,0);await shopAction(req(),{action:"seller-status",id:actorA.userId,active:false});await assert.rejects(()=>shopAction(req(ac),{action:"seller-save",name:"blocked",kind:"KEY",price:10000}),/bị khóa/);assert.equal(db.prepare("SELECT enabled FROM products WHERE code='seller-key'").get().enabled,0);passed("Sales scoped to seller; revoking rights disables sale and seller writes");
 await shopAction(req(),{action:"seller-status",id:actorA.userId,active:true});for(const [cookie,code,host] of [[ac,"seller-proxy-a","8.8.6.1"],[bc,"seller-proxy-b","8.8.6.2"]]){await shopAction(req(cookie),{action:"seller-save",code,name:code,kind:"PROXY",protocol:"HTTP",price:10000,description:"Fixture"});await shopAction(req(cookie),{action:"seller-import",product:code,text:`${host}:8000:fixture:fixture-pass`});await shopAction(req(),{action:"seller-review",code,approve:true});}
 globalThis.__shopUser=buyer;const proxyId=crypto.randomUUID();await shopAction(req(),{action:"create-order",product:"seller-proxy-a",quantity:1,requestId:proxyId});const proxyOrder=db.prepare("SELECT id FROM orders WHERE request_id=?").get(proxyId).id;globalThis.__shopUser=owner;await shopAction(req(),{action:"approve",id:proxyOrder});assert.equal(db.prepare("SELECT p.host FROM slots s JOIN stock p ON p.id=s.stock_id WHERE s.order_id=?").get(proxyOrder).host,"8.8.6.1");globalThis.__health["8.8.6.1"]=false;for(let i=0;i<3;i++){now+=300001;await maintenance();}assert.equal(db.prepare("SELECT p.host FROM slots s JOIN stock p ON p.id=s.stock_id WHERE s.order_id=?").get(proxyOrder).host,"8.8.6.1");assert.equal(db.prepare("SELECT state FROM stock WHERE host='8.8.6.2'").get().state,"AVAILABLE");passed("Proxy delivery and warranty cannot consume a different seller's reserve");
 await shopAction(req(bc),{action:"seller-save",code:"seller-wallet",name:"Wallet fixture",kind:"KEY",price:2000,description:"Fixture"});await shopAction(req(bc),{action:"seller-import",product:"seller-wallet",text:"wallet-fixture-1\nwallet-fixture-2"});await shopAction(req(),{action:"seller-review",code:"seller-wallet",approve:true});db.prepare("INSERT INTO wallet_entries(id,customer_id,amount,kind,reference,created) VALUES('fixture-credit',?,10000,'TOPUP','fixture-credit',?)").run(buyer.userId,now);
 globalThis.__shopUser=buyer;const walletId=crypto.randomUUID();const walletOrder=await shopAction(req(),{action:"wallet-order",product:"seller-wallet",quantity:1,requestId:walletId});await shopAction(req(),{action:"wallet-order",product:"seller-wallet",quantity:1,requestId:walletId});assert.equal(db.prepare("SELECT COUNT(*) n FROM seller_sales WHERE order_id=?").get(walletOrder.orderId).n,1);assert.equal(db.prepare("SELECT fee FROM seller_sales WHERE order_id=?").get(walletOrder.orderId).fee,100);assert.equal(db.prepare("SELECT SUM(amount) balance FROM wallet_entries WHERE customer_id=?").get(buyer.userId).balance,8000);passed("Wallet sale charges once and records seller fee once across retries");
 db.exec("CREATE TRIGGER fee_failure BEFORE INSERT ON seller_sales BEGIN SELECT RAISE(ABORT,'fixture fee failure'); END");await assert.rejects(()=>shopAction(req(),{action:"wallet-order",product:"seller-wallet",quantity:1,requestId:crypto.randomUUID()}),/fixture fee failure/);assert.equal(db.prepare("SELECT SUM(amount) balance FROM wallet_entries WHERE customer_id=?").get(buyer.userId).balance,8000);assert.equal(db.prepare("SELECT COUNT(*) n FROM digital_stock WHERE product='seller-wallet' AND state='AVAILABLE'").get().n,1);db.exec("DROP TRIGGER fee_failure");passed("Fee accounting failure rolls back customer debit and stock delivery together");
 db.prepare("UPDATE auth_sessions SET expires=0 WHERE customer_id=?").run(actorB.userId);assert.equal(await localIdentity(database,req(bc)),null);passed("Expired session cannot authenticate");
 console.log(`${count} auth, price and CTV checks passed; isolated fixtures only.`);
}finally{Date.now=originalNow;globalThis.fetch=originalFetch;db.close();}
