import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {build} from "esbuild";
import net from "node:net";
import {pathToFileURL} from "node:url";

fs.mkdirSync(".sites-runtime/tests",{recursive:true});
const aliases={"cloudflare:workers":"env.mjs","@/app/chatgpt-auth":"identity.mjs","./proxy-checker":"checker.mjs"};
await build({entryPoints:["lib/shop-service.ts"],outfile:".sites-runtime/tests/service.mjs",bundle:true,platform:"node",format:"esm",plugins:[{name:"test-boundaries",setup(b){b.onResolve({filter:/.*/},args=>aliases[args.path]?{path:path.resolve("tests/fixtures",aliases[args.path])}:null);}}]});
await build({entryPoints:["lib/proxy-checker.ts"],outfile:".sites-runtime/tests/checker.mjs",bundle:true,platform:"node",format:"esm",plugins:[{name:"test-socket",setup(b){b.onResolve({filter:/^cloudflare:sockets$/},()=>({path:path.resolve("tests/fixtures/socket.mjs")}));}}]});
const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const migration of fs.readdirSync("drizzle").filter(f=>f.endsWith(".sql")).sort())db.exec(fs.readFileSync(path.join("drizzle",migration),"utf8"));
class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args;}bind(...args){return new Statement(this.sql,args);}async first(){return db.prepare(this.sql).get(...this.args)??null;}async all(){return {results:db.prepare(this.sql).all(...this.args)};}async run(){const result=db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(result.changes)}};}}
globalThis.__shopEnv={DB:{prepare:sql=>new Statement(sql),batch:async statements=>{db.exec("BEGIN IMMEDIATE");try{const results=[];for(const s of statements)results.push(await s.run());db.exec("COMMIT");return results;}catch(e){db.exec("ROLLBACK");throw e;}}},ADMIN_EMAIL:"owner@example.test",PROXY_ENCRYPTION_KEY:"a1".repeat(32)};
globalThis.__health={};
const owner={userId:"owner",email:"owner@example.test",displayName:"Owner"},customer={userId:"buyer",email:"buyer@example.test",displayName:"Buyer"},stranger={userId:"stranger",email:"other@example.test",displayName:"Other"};
globalThis.__shopUser=owner;
let now=1800000000000;const originalNow=Date.now,originalFetch=globalThis.fetch;Date.now=()=>now;globalThis.fetch=async()=>new Response(null,{status:204});
const {shopAction,shopSnapshot,maintenance}=await import(pathToFileURL(path.resolve(".sites-runtime/tests/service.mjs")));
const request=new Request("https://shop.test/api/shop",{method:"POST",headers:{origin:"https://shop.test"}});
const action=payload=>shopAction(request,payload);
let tests=0;
const passed=name=>{tests++;console.log(`PASS ${name}`);};
try{
 await assert.rejects(()=>action({action:"import",protocol:"HTTP",text:"127.0.0.1:8000:u:p"}),/Dòng 1/);passed("Reject private-network proxy imports");
 await action({action:"settings",paymentInstructions:"Chuyển khoản theo hướng dẫn của chủ cửa hàng, ghi PH + mã đơn.",products:[{code:"ipv4",price:30000,enabled:true},{code:"socks5",price:35000,enabled:true}]});
 await action({action:"import",protocol:"HTTP",text:"8.8.4.1:8000:fixture:fixture-pass\n8.8.4.2:8000:fixture:fixture-pass\n8.8.4.3:8000:fixture:fixture-pass\n8.8.4.4:8000:fixture:fixture-pass"});
 await action({action:"import",protocol:"HTTP",text:"8.8.4.1:8000:fixture:fixture-pass"});assert.equal(db.prepare("SELECT count(*) n FROM stock").get().n,4);assert(!db.prepare("SELECT credentials FROM stock LIMIT 1").get().credentials.includes("fixture-pass"));passed("Deduplicate imports and encrypt credentials");
 globalThis.__shopUser=customer;const rid=crypto.randomUUID();await action({action:"create-order",product:"ipv4",quantity:2,requestId:rid});await action({action:"create-order",product:"ipv4",quantity:2,requestId:rid});assert.equal(db.prepare("SELECT count(*) n FROM orders").get().n,1);passed("Idempotent order creation");
 await assert.rejects(()=>action({action:"settings",products:[]}),/quản trị viên/);passed("Customer cannot access admin writes");
 const order=db.prepare("SELECT id FROM orders").get().id;globalThis.__shopUser=owner;
 Object.assign(globalThis.__health,{"8.8.4.2":false,"8.8.4.3":false,"8.8.4.4":false});await assert.rejects(()=>action({action:"approve",id:order}),/chưa đủ/);assert.equal(db.prepare("SELECT count(*) n FROM slots").get().n,0);assert.equal(db.prepare("SELECT status FROM orders").get().status,"PENDING");passed("Insufficient live stock preserves pending order");
 globalThis.__health={};const concurrent=await Promise.allSettled([action({action:"approve",id:order}),action({action:"approve",id:order})]);assert.equal(concurrent.filter(r=>r.status==="fulfilled").length,1);const slots=db.prepare("SELECT * FROM slots ORDER BY position").all();assert.equal(slots.length,2);assert.notEqual(slots[0].stock_id,slots[1].stock_id);assert.equal(slots[0].expires,now+30*86400000);await assert.rejects(()=>action({action:"approve",id:order}),/trạng thái chờ/);passed("Concurrent approval serialized: distinct proxies and exact 30-day warranty");
 globalThis.__shopUser=customer;const one=await action({action:"export",ids:[slots[0].id]});assert.equal(one.text.split("\n").length,1);const full=await action({action:"export",ids:slots.map(s=>s.id)});assert.equal(full.text.split("\n").length,2);passed("Single-row copy exports only one proxy when customer owns multiple");
 globalThis.__shopUser=stranger;await assert.rejects(()=>action({action:"export",ids:[slots[0].id]}),/Không có proxy/);assert.equal((await shopSnapshot()).proxies.length,0);passed("Ownership enforced for list and TXT export");
 globalThis.__shopUser=customer;const result=await action({action:"export",ids:[slots[0].id]});assert.match(result.text,/:fixture:fixture-pass$/);passed("Owner exports full current credentials");
 const old=db.prepare("SELECT * FROM stock WHERE id=?").get(slots[0].stock_id);globalThis.__health[old.host]=false;
 now+=300001;await maintenance();now+=300001;await maintenance();assert.equal(db.prepare("SELECT stock_id FROM slots WHERE id=?").get(slots[0].id).stock_id,old.id);assert.equal(db.prepare("SELECT archived FROM stock WHERE id=?").get(old.id).archived,0);passed("Two failures do not trigger replacement or remove proxy from inventory");
 await maintenance();assert.equal(db.prepare("SELECT failures FROM stock WHERE id=?").get(old.id).failures,2);passed("Repeated checks inside cooldown do not count again");
 globalThis.__health={};globalThis.__health[old.host]=false;for(const p of db.prepare("SELECT host FROM stock WHERE state='AVAILABLE'").all())globalThis.__health[p.host]=false;
 now+=300001;await maintenance();assert.equal(db.prepare("SELECT stock_id FROM slots WHERE id=?").get(slots[0].id).stock_id,old.id);assert.equal(db.prepare("SELECT count(*) n FROM notifications WHERE dedupe LIKE 'missing:%'").get().n,1);assert.equal(db.prepare("SELECT archived FROM stock WHERE id=?").get(old.id).archived,1);passed("Confirmed dead proxy automatically archived; retain customer slot and notify without reserve");
 for(const p of db.prepare("SELECT host FROM stock WHERE state='AVAILABLE'").all())globalThis.__health[p.host]=true;
 now+=300001;await maintenance();const after=db.prepare("SELECT * FROM slots WHERE id=?").get(slots[0].id);assert.notEqual(after.stock_id,old.id);assert.equal(after.position,slots[0].position);assert.equal(after.expires,slots[0].expires);assert.equal(db.prepare("SELECT state FROM stock WHERE id=?").get(old.id).state,"QUARANTINED");assert.equal(db.prepare("SELECT count(*) n FROM warranty").get().n,1);passed("Third spaced failure replaces same line and preserves expiry");
 globalThis.__shopUser=customer;const updated=await action({action:"export",ids:[after.id]});assert(!updated.text.startsWith(old.host+":"));passed("Customer TXT immediately reflects replacement");
 const beforeFailure=db.prepare("SELECT failures FROM stock WHERE id=?").get(after.stock_id).failures;globalThis.fetch=async()=>new Response(null,{status:500});now+=300001;await assert.rejects(maintenance,/Chưa kết luận proxy die/);assert.equal(db.prepare("SELECT failures FROM stock WHERE id=?").get(after.stock_id).failures,beforeFailure);passed("Checker network outage does not mark customer proxies dead");globalThis.fetch=async()=>new Response(null,{status:204});
 now=after.expires+1;await maintenance();globalThis.__shopUser=customer;await assert.rejects(()=>action({action:"export",ids:[after.id]}),/Không có proxy/);passed("Expired leases are excluded from export and replacement");
 // SQL guard verifies a failed precondition rolls back all prior writes in the batch.
 const countBefore=db.prepare("SELECT count(*) n FROM runs").get().n;
 await assert.rejects(()=>globalThis.__shopEnv.DB.batch([new Statement("INSERT INTO runs(id,created,checked,replaced,message) VALUES('rollback',1,0,0,'test')"),new Statement("INSERT INTO transaction_guards(id,valid) VALUES('invalid',0)")]));assert.equal(db.prepare("SELECT count(*) n FROM runs").get().n,countBefore);passed("Failed transaction guard rolls back entire batch");
 globalThis.__shopUser=customer;await assert.rejects(()=>action({action:"save-product",name:"Blocked",kind:"ACCOUNT",price:10000,enabled:true}),/quản trị viên/);passed("Customer cannot create products or import stock");
 globalThis.__shopUser=owner;
 for(const kind of ["ACCOUNT","KEY","TEXT","LINK","FILE_LINK"]){
  const code="fixture-"+kind.toLowerCase();await action({action:"save-product",code,name:"Fixture "+kind,kind,description:"Test fixture",price:10000,enabled:true});
  const content=kind.includes("LINK")?"https://example.test/"+kind.toLowerCase():"fixture-"+kind+":fixture-pass";
  await action({action:"import-items",product:code,text:content+"\n"+content});assert.equal(db.prepare("SELECT count(*) n FROM digital_stock WHERE product=?").get(code).n,1);assert(!db.prepare("SELECT content FROM digital_stock WHERE product=?").get(code).content.includes("fixture-pass"));
  globalThis.__shopUser=customer;await action({action:"create-order",product:code,quantity:1,requestId:crypto.randomUUID()});const digitalOrder=db.prepare("SELECT id FROM orders WHERE product=?").get(code).id;
  globalThis.__shopUser=owner;const dual=await Promise.allSettled([action({action:"approve",id:digitalOrder}),action({action:"approve",id:digitalOrder})]);assert.equal(dual.filter(x=>x.status==="fulfilled").length,1);
  const delivery=db.prepare("SELECT id FROM deliveries WHERE order_id=?").get(digitalOrder).id;
  globalThis.__shopUser=stranger;await assert.rejects(()=>action({action:"export-items",ids:[delivery]}),/Không có sản phẩm/);
  globalThis.__shopUser=customer;assert.equal((await action({action:"export-items",ids:[delivery]})).text,content);assert((await shopSnapshot()).purchases.some(p=>p.id===delivery));
  assert.equal(db.prepare("SELECT state FROM digital_stock WHERE product=?").get(code).state,"ASSIGNED");
  globalThis.__shopUser=owner;passed(kind+" delivery: encrypted, deduplicated, assigned once and buyer-only export");
 }
 await assert.rejects(()=>action({action:"import-items",product:"fixture-link",text:"javascript:alert(1)"}),/HTTP/);passed("Reject executable links");
 globalThis.__shopUser=customer;await action({action:"create-order",product:"fixture-account",quantity:2,requestId:crypto.randomUUID()});const emptyOrder=db.prepare("SELECT id FROM orders WHERE product='fixture-account' AND status='PENDING'").get().id;
 globalThis.__shopUser=owner;await assert.rejects(()=>action({action:"approve",id:emptyOrder}),/chưa đủ/);assert.equal(db.prepare("SELECT status FROM orders WHERE id=?").get(emptyOrder).status,"PENDING");passed("Sold stock cannot be sold again; insufficient stock retains pending order");
 await action({action:"settings",paymentInstructions:"Chuyển khoản theo hướng dẫn của chủ cửa hàng, ghi PH + mã đơn.",products:[{code:"ipv4",price:30000,enabled:true},{code:"socks5",price:35000,enabled:true}]});assert.equal(db.prepare("SELECT count(*) n FROM products WHERE kind<>'PROXY'").get().n,5);passed("Proxy settings preserve digital catalog");

 globalThis.__shopUser=customer;await assert.rejects(()=>action({action:"sepay-settings",enabled:true}),/quản trị viên/);passed("Customers cannot edit SePay settings");
 const bankId="11111111-1111-4111-8111-111111111111";let receipts=[],apiFails=false;
 let bankActive=1; globalThis.fetch=async(url,options)=>{const parsed=new URL(String(url));if(parsed.hostname==="userapi.sepay.vn"){assert.equal(options.headers.Authorization,"Bearer fixture-sepay-token");if(apiFails)return new Response(null,{status:401});if(parsed.pathname==="/v2/bank-accounts")return Response.json({status:"success",data:[{id:bankId,account_number:"fixture-bank-account",account_holder_name:"Fixture Owner",bank_short_name:"FIXTURE",active:bankActive}]});if(parsed.pathname.includes("bank-accounts"))return Response.json({status:"success",data:{id:bankId,account_number:"fixture-bank-account",account_holder_name:"Fixture Owner",bank_short_name:"FIXTURE",active:bankActive}});assert.equal(parsed.pathname,"/v2/transactions");return Response.json({status:"success",data:receipts});}return new Response(null,{status:204});};
 globalThis.__shopUser=owner;const bankList=await action({action:"sepay-banks",token:"fixture-sepay-token"});assert.equal(bankList.banks[0].id,bankId);passed("Admin selects verified bank without exposing balances or token");await action({action:"sepay-settings",enabled:true,bankId,token:"fixture-sepay-token"});assert(!db.prepare("SELECT value FROM shop_settings WHERE key='sepay_config'").get().value.includes("fixture-sepay-token"));assert(!JSON.stringify(await shopSnapshot()).includes("fixture-sepay-token"));passed("Verify bank via SePay; token encrypted and excluded from snapshots");
 for(const activeValue of [true,1,"1","true"]){bankActive=activeValue;await action({action:"sepay-settings",enabled:true,bankId,token:"fixture-sepay-token"});}passed("SePay active boolean and explicit numeric/string variants accepted");
 for(const activeValue of [false,0,"0","false",null,undefined,"yes"]){bankActive=activeValue;await assert.rejects(()=>action({action:"sepay-settings",enabled:true,bankId,token:"fixture-sepay-token"}),/chưa hoạt động/);}bankActive=1;passed("Inactive or malformed bank state never enables payment");
 globalThis.__shopUser=customer;const topupRequest=crypto.randomUUID();const deposit=await action({action:"create-topup",amount:100000,requestId:topupRequest});await action({action:"create-topup",amount:100000,requestId:topupRequest});assert.equal(db.prepare("SELECT count(*) n FROM topups").get().n,1);let pendingTopup=db.prepare("SELECT * FROM topups WHERE id=?").get(deposit.id);passed("Top-up creation retries do not create another payment code");
 globalThis.__shopUser=stranger;await assert.rejects(()=>action({action:"check-topup",id:deposit.id}),/Không tìm thấy/);globalThis.__shopUser=customer;passed("Top-up checking scoped to owner");
 const receiptFor=p=>({id:crypto.randomUUID(),bank_account_id:bankId,account_number:"fixture-bank-account",transfer_type:"in",amount_in:p.amount,amount_out:0,transaction_date:new Date(now).toISOString(),transaction_content:"Transfer "+p.code,code:p.code});
 receipts=[{...receiptFor(pendingTopup),account_number:"other-account"},{...receiptFor(pendingTopup),transfer_type:"out",amount_in:0,amount_out:100000},{...receiptFor(pendingTopup),transaction_content:"Wrong code",code:null}];await action({action:"check-topup",id:deposit.id});assert.equal((await shopSnapshot()).wallet.balance,0);passed("Wrong account, outgoing transfer and unmatched code never credit");
 now+=16000;apiFails=true;await assert.rejects(()=>action({action:"check-topup",id:deposit.id}),/Token/);assert.equal((await shopSnapshot()).wallet.balance,0);apiFails=false;passed("SePay API errors preserve wallet balance");
 now+=16000;receipts=[receiptFor(pendingTopup)];await action({action:"check-topup",id:deposit.id});await action({action:"check-topup",id:deposit.id});assert.equal((await shopSnapshot()).wallet.balance,100000);assert.equal(db.prepare("SELECT count(*) n FROM wallet_entries").get().n,1);passed("Exact verified deposit credited once across retries");
 globalThis.__shopUser=owner;await action({action:"import-items",product:"fixture-account",text:"wallet-fixture-1:fixture-pass\nwallet-fixture-2:fixture-pass"});globalThis.__shopUser=customer;const buyRequest=crypto.randomUUID();const bought=await action({action:"wallet-order",product:"fixture-account",quantity:1,requestId:buyRequest});assert(bought.delivered);assert.equal((await shopSnapshot()).wallet.balance,90000);await action({action:"wallet-order",product:"fixture-account",quantity:1,requestId:buyRequest});assert.equal((await shopSnapshot()).wallet.balance,90000);assert.equal(db.prepare("SELECT count(*) n FROM wallet_entries WHERE kind='PURCHASE'").get().n,1);passed("Wallet purchase atomically delivers and charges once");
 const balanceBeforeFailure=(await shopSnapshot()).wallet.balance,originalBatch=globalThis.__shopEnv.DB.batch;
 globalThis.__shopEnv.DB.batch=async statements=>originalBatch(statements.some(x=>x.sql.includes("INSERT INTO wallet_entries"))?[...statements,new Statement("INSERT INTO transaction_guards(id,valid) VALUES('force-wallet-rollback',0)")]:statements);
 try{await assert.rejects(()=>action({action:"wallet-order",product:"fixture-account",quantity:1,requestId:crypto.randomUUID()}));}finally{globalThis.__shopEnv.DB.batch=originalBatch;}
 assert.equal((await shopSnapshot()).wallet.balance,balanceBeforeFailure);assert.equal(db.prepare("SELECT count(*) n FROM digital_stock WHERE product='fixture-account' AND state='AVAILABLE'").get().n,1);passed("Database failure rolls back debit and delivery together");
 const beforeWallet=(await shopSnapshot()).wallet.balance;await assert.rejects(()=>action({action:"wallet-order",product:"fixture-account",quantity:2,requestId:crypto.randomUUID()}),/chưa đủ/);assert.equal((await shopSnapshot()).wallet.balance,beforeWallet);passed("Insufficient digital stock does not debit wallet");
 globalThis.__shopUser=owner;const pendingWallet=db.prepare("SELECT id FROM orders WHERE payment_method='WALLET' AND status='PENDING'").get();await assert.rejects(()=>action({action:"approve",id:pendingWallet.id}),/không duyệt tay/);passed("Manual approval cannot bypass wallet payment");
 await action({action:"import",protocol:"HTTP",text:"8.8.5.1:8000:fixture:fixture-pass"});globalThis.__health["8.8.5.1"]=true;globalThis.__shopUser=customer;await action({action:"wallet-order",product:"ipv4",quantity:1,requestId:crypto.randomUUID()});assert.equal((await shopSnapshot()).wallet.balance,60000);passed("Wallet proxy purchase verifies live before atomic charge and delivery");
 globalThis.__shopUser=stranger;await assert.rejects(()=>action({action:"wallet-order",product:"ipv4",quantity:1,requestId:crypto.randomUUID()}),/Số dư/);assert.equal((await shopSnapshot()).wallet.balance,0);globalThis.__shopUser=customer;passed("No spending another customer's wallet");
 const mismatch=await action({action:"create-topup",amount:10000,requestId:crypto.randomUUID()});pendingTopup=db.prepare("SELECT * FROM topups WHERE id=?").get(mismatch.id);receipts=[{...receiptFor(pendingTopup),amount_in:9999}];await action({action:"check-topup",id:mismatch.id});assert.equal(db.prepare("SELECT status FROM topups WHERE id=?").get(mismatch.id).status,"REVIEW");assert.equal((await shopSnapshot()).wallet.balance,60000);passed("Amount mismatch goes to review without credit");
 const late=await action({action:"create-topup",amount:10000,requestId:crypto.randomUUID()});pendingTopup=db.prepare("SELECT * FROM topups WHERE id=?").get(late.id);receipts=[{...receiptFor(pendingTopup),transaction_date:new Date(pendingTopup.expires+1).toISOString()}];await action({action:"check-topup",id:late.id});assert.equal(db.prepare("SELECT status FROM topups WHERE id=?").get(late.id).status,"REVIEW");assert.equal((await shopSnapshot()).wallet.balance,60000);passed("Late transfer is reviewed rather than blindly credited");
 globalThis.__shopUser=owner;await action({action:"sepay-settings",enabled:false});globalThis.__shopUser=customer;await assert.rejects(()=>action({action:"create-topup",amount:10000,requestId:crypto.randomUUID()}),/chưa được bật/);assert.equal((await shopSnapshot()).wallet.balance,60000);passed("Disabling SePay preserves customer funds");

 await assert.rejects(()=>action({action:"manual-topup",id:mismatch.id,confirmed:true,bankReference:"TESTBANK1234",reason:"Fixture receipt"}),/quản trị/);
 globalThis.__shopUser=owner;assert.equal((await shopSnapshot()).wallet.review.length,0);await assert.rejects(()=>action({action:"manual-topup",id:mismatch.id,confirmed:true,bankReference:"TESTBANK1234",reason:"Fixture receipt"}),/chưa gửi/);globalThis.__shopUser=stranger;await assert.rejects(()=>action({action:"confirm-topup",id:mismatch.id}),/Không tìm thấy/);
 globalThis.__shopUser=customer;await action({action:"confirm-topup",id:mismatch.id});globalThis.__shopUser=owner;assert.equal((await shopSnapshot()).wallet.review.length,1);passed("Only customer-confirmed requests enter admin review; ownership and admin permissions enforced");
 await assert.rejects(()=>action({action:"manual-topup",id:mismatch.id,confirmed:false,bankReference:"TESTBANK1234",reason:"Fixture receipt"}),/Xác nhận/);await action({action:"manual-topup",id:mismatch.id,confirmed:true,bankReference:"TESTBANK1234",reason:"Fixture received payment",amount:999999});await action({action:"manual-topup",id:mismatch.id,confirmed:true,bankReference:"TESTBANK5678",reason:"Retry"});assert.equal(db.prepare("SELECT COUNT(*) n FROM manual_topup_approvals WHERE topup_id=?").get(mismatch.id).n,1);globalThis.__shopUser=customer;assert.equal((await shopSnapshot()).wallet.balance,70000);assert.equal((await shopSnapshot()).wallet.approvals.length,0);await action({action:"confirm-topup",id:late.id});globalThis.__shopUser=owner;await assert.rejects(()=>action({action:"manual-topup",id:late.id,confirmed:true,bankReference:"testbank1234",reason:"Duplicate"}),/đã dùng/);assert.equal((await shopSnapshot()).wallet.approvals[0].actor_email,owner.email);passed("Manual credit uses stored amount, records actor, is idempotent and rejects reused bank references");
 await action({action:"sepay-settings",enabled:true,bankId});globalThis.__shopUser=customer;const duplicateReceipt=await action({action:"create-topup",amount:10000,requestId:crypto.randomUUID()});pendingTopup=db.prepare("SELECT * FROM topups WHERE id=?").get(duplicateReceipt.id);receipts=[{...receiptFor(pendingTopup),reference_number:"TESTBANK1234"}];await action({action:"check-topup",id:duplicateReceipt.id});assert.equal((await shopSnapshot()).wallet.balance,70000);passed("Auto reconciliation cannot reuse a bank reference already credited manually");

}finally{Date.now=originalNow;globalThis.fetch=originalFetch;db.close();}

const {checkProxy}=await import(pathToFileURL(path.resolve(".sites-runtime/tests/checker.mjs")));
async function testServer(handler,work){const sockets=new Set();const server=net.createServer(s=>{sockets.add(s);s.on("close",()=>sockets.delete(s));handler(s);});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));globalThis.__proxyTestPort=server.address().port;try{await work();}finally{for(const s of sockets)s.destroy();await new Promise(resolve=>server.close(resolve));}}
await testServer(s=>s.once("data",chunk=>{assert.match(chunk.toString(),/Proxy-Authorization: Basic/);s.write("HTTP/1.1 204 No Content\r\n");setTimeout(()=>s.write("Connection: close\r\n\r\n"),5);}),async()=>{const r=await checkProxy({host:"8.8.8.8",port:8000,protocol:"HTTP",user:"fixture",password:"fixture-pass"});assert(r.ok);});passed("HTTP proxy authentication and fragmented response over real TCP");
await testServer(s=>{let stage=0;s.on("data",chunk=>{if(stage===0){assert.equal(chunk[0],5);s.write(Buffer.from([5,2]));}else if(stage===1){assert.equal(chunk[0],1);s.write(Buffer.from([1,0]));}else if(stage===2){assert.equal(chunk[0],5);s.write(Buffer.from([5,0,0,1,127,0,0,1,0,80]));}else{s.write("HTTP/1.1 204 No Content\r\n\r\n");}stage++;});},async()=>{const r=await checkProxy({host:"8.8.8.8",port:1080,protocol:"SOCKS5",user:"fixture",password:"fixture-pass"});assert(r.ok);});passed("SOCKS5 auth and tunnel handshake over real TCP");
await testServer(s=>s.once("data",()=>s.write("HTTP/1.1 407 Proxy Authentication Required\r\n\r\n")),async()=>{const r=await checkProxy({host:"8.8.8.8",port:8000,protocol:"HTTP",user:"fixture",password:"wrong"});assert(!r.ok);assert.equal(r.error,"Sai xác thực proxy");});passed("Authentication rejection is never reported live");
await build({entryPoints:["lib/wallet.ts"],outfile:".sites-runtime/tests/wallet.mjs",bundle:true,platform:"node",format:"esm"});
const {matchingTransaction}=await import(pathToFileURL(path.resolve(".sites-runtime/tests/wallet.mjs")));
const vaTopup={code:"PHN"+"A".repeat(20),amount:10000,bank_id:crypto.randomUUID(),account_number:"96886693012414",va_id:crypto.randomUUID(),parent_account_number:"80003158010",created:Date.now()-1000,expires:Date.now()+60000};
const vaReceipt={id:crypto.randomUUID(),bank_account_id:vaTopup.bank_id,account_number:vaTopup.parent_account_number,va:vaTopup.account_number,va_id:vaTopup.va_id,amount_in:10000,amount_out:0,transfer_type:"in",transaction_date:new Date().toISOString(),transaction_content:vaTopup.code};
assert.equal(matchingTransaction(vaReceipt,vaTopup),"MATCH");
for(const change of [{va:"other"},{va_id:crypto.randomUUID()},{account_number:"other"},{va:null,va_id:null}])assert.equal(matchingTransaction({...vaReceipt,...change},vaTopup),"IGNORE");
passed("VA deposits require exact parent bank, parent account, VA ID and VA number");
console.log(`${tests} checks passed. All test data is isolated; no production records or real user proxies used.`);
