"use client";
import {useState} from "react";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "./ui/dialog";
export async function logoutLocal(){const response=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});if(!response.ok)throw new Error("Chưa đăng xuất được. Thử lại.");}
export function AuthDialog({mode,setMode,onDone}:{mode:"login"|"register"|null;setMode:(mode:"login"|"register"|null)=>void;onDone:()=>Promise<void>}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <Dialog open={mode!==null} onOpenChange={open=>{if(!open){setMode(null);setPassword("");setError("");}}}><DialogContent className="proxy-dialog"><DialogHeader><DialogTitle>{mode==="register"?"Đăng ký tài khoản":"Đăng nhập"}</DialogTitle><DialogDescription>Dùng email và mật khẩu riêng của ProxyHub.</DialogDescription></DialogHeader><form className="dialog-body" onSubmit={async e=>{e.preventDefault();setError("");setBusy(true);try{const response=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode,email,password,name})}),result=await response.json() as {error?:string;message?:string};if(!response.ok)throw new Error(result.error??"Không đăng nhập được.");setPassword("");await onDone();setMode(null);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{mode==="register"&&<label>Tên hiển thị<Input value={name} required minLength={2} maxLength={80} autoComplete="name" onChange={e=>setName(e.target.value)}/></label>}<label>Email<Input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu<Input type="password" required minLength={mode==="register"?8:1} maxLength={128} autoComplete={mode==="register"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==="register"&&<small>Mật khẩu từ 8 ký tự. Quyền CTV được chủ cửa hàng cấp riêng.</small>}{error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={busy} type="submit">{busy?"Đang xử lý...":mode==="register"?"Tạo tài khoản":"Đăng nhập"}</Button><Button type="button" variant="outline" onClick={()=>{setMode(mode==="register"?"login":"register");setError("");setPassword("");}}>{mode==="register"?"Đã có tài khoản? Đăng nhập":"Chưa có tài khoản? Đăng ký"}</Button></form></DialogContent></Dialog>;
}

