"use client";
import {MoneyField} from "./money-field";
import {moneyValue} from "@/lib/money-input";
import {useState} from "react";
import type {Shop,Product} from "./shop-dashboard";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Package,Plus,Pencil,Upload,Copy,Download} from "lucide-react";
export const kindNames:Record<string,string>={ACCOUNT:"Tài khoản",KEY:"Mã key",TEXT:"Nội dung text",LINK:"Link",FILE_LINK:"Link tải file",PROXY:"Proxy CTV"};
const money=(n:number)=>n.toLocaleString("vi-VN")+" đ";
export function DigitalCatalog({shop,onChoose,onNotice}:{shop:Shop;onChoose:(code:string)=>void;onNotice:(text:string)=>void}){
 const admin=!!shop.data?.user?.isAdmin,products=(shop.data?.products??[]).filter(p=>(p.kind!=="PROXY"||!!p.seller_id)&&(admin||p.enabled));
 const [draft,setDraft]=useState<{code:string;name:string;kind:string;description:string;price:string;enabled:boolean}|null>(null),[importProduct,setImportProduct]=useState<Product|null>(null),[text,setText]=useState(""),[error,setError]=useState("");
 function edit(p?:Product){setError("");setDraft({code:p?.code??"",name:p?.name??"",kind:p?.kind??"ACCOUNT",description:p?.description??"",price:String(p?.price??""),enabled:p?.enabled??false});}
 const stock=(code:string)=>shop.data?.digitalInventory?.find(i=>i.code===code);
 return <section className="digital-catalog"><div className="panel-heading"><h3>Sản phẩm khác</h3>{admin&&<Button size="sm" onClick={()=>edit()}><Plus size={14}/> Thêm sản phẩm</Button>}</div>
 <div className="digital-grid">{products.map(p=><article key={p.code} className="data-panel digital-card"><Package size={22}/><span className="protocol-badge">{kindNames[p.kind]??p.kind}</span><h3>{p.name}</h3><p>{p.description||"Mỗi sản phẩm được giao từ kho sau khi xác nhận thanh toán."}</p><strong>{money(p.price)} / sản phẩm</strong>{admin&&<small>Kho còn {stock(p.code)?.available??0} · Đã nhập {stock(p.code)?.total??0} · {p.enabled?"Đang bán":"Tạm tắt"}</small>}<div className="panel-actions"><Button size="sm" disabled={!p.enabled} onClick={()=>onChoose(p.code)}>Mua</Button>{admin&&!p.seller_id&&<><Button size="sm" variant="outline" onClick={()=>edit(p)}><Pencil size={13}/> Sửa</Button><Button size="sm" variant="outline" onClick={()=>{setImportProduct(p);setText("");setError("");}}><Upload size={13}/> Nhập kho</Button></>}</div></article>)}</div>
 {!products.length&&<div className="empty-state"><Package/><h4>{admin?"Chưa có sản phẩm khác":"Chưa có sản phẩm đang mở bán"}</h4>{admin&&<p>Thêm sản phẩm, chọn loại giao hàng rồi nhập list vào kho riêng.</p>}</div>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open){setDraft(null);setError("");}}}><DialogContent className="proxy-dialog"><DialogHeader><DialogTitle>{draft?.code?"Sửa sản phẩm":"Thêm sản phẩm"}</DialogTitle><DialogDescription>Tài khoản, key hoặc link: mỗi dòng trong kho là một sản phẩm bán riêng.</DialogDescription></DialogHeader>{draft&&<div className="dialog-body"><label>Tên sản phẩm<Input value={draft.name} maxLength={100} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Loại giao hàng<select disabled={!!draft.code} value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{Object.entries(kindNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Mô tả<Textarea value={draft.description} maxLength={2000} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Giá mỗi sản phẩm (đ)<MoneyField value={draft.price} onChange={price=>setDraft({...draft,price})}/></label><label className="toggle-selling"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/> Mở bán</label><p className="muted">Nhập kho trước khi mở bán. Sản phẩm khác không có kiểm tra live hoặc tự bảo hành như proxy.</p>{error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={shop.busy||!draft.name.trim()||draft.price===""} onClick={async()=>{try{const r=await shop.action({action:"save-product",...draft,price:moneyValue(draft.price)});onNotice(r.message??"Đã lưu.");setDraft(null);}catch(e){setError((e as Error).message);}}}>Lưu sản phẩm</Button></div>}</DialogContent></Dialog>
 <Dialog open={!!importProduct} onOpenChange={open=>{if(!open){setImportProduct(null);setText("");setError("");}}}><DialogContent className="proxy-dialog"><DialogHeader><DialogTitle>Nhập kho · {importProduct?.name}</DialogTitle><DialogDescription>Kho riêng của sản phẩm. Một dòng = một đơn vị; dòng trùng sẽ bỏ qua.</DialogDescription></DialogHeader><div className="dialog-body"><label>Danh sách<Textarea rows={8} value={text} onChange={e=>setText(e.target.value)} placeholder={importProduct?.kind==="ACCOUNT"?"user:pass — một tài khoản mỗi dòng":importProduct?.kind==="KEY"?"Một key mỗi dòng":"Một nội dung hoặc link mỗi dòng"}/></label><label>Nhập từ file TXT<Input type="file" accept=".txt,text/plain" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>200000){setError("File tối đa 200 KB.");return;}setText(await file.text());}}/></label><p className="muted">Tối đa 500 dòng mỗi lần nhập. Với file tải về, nhập link tải file đã được lưu trên dịch vụ của bạn.</p>{error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={shop.busy||!text.trim()} onClick={async()=>{try{const r=await shop.action({action:"import-items",product:importProduct?.code,text});onNotice(r.message??"Đã nhập kho.");setImportProduct(null);setText("");}catch(e){setError((e as Error).message);}}}>Nhập vào kho</Button></div></DialogContent></Dialog></section>;
}
export function DigitalPurchases({shop,onCopy,onDownload}:{shop:Shop;onCopy:(ids:string[])=>void;onDownload:(ids:string[])=>void}){
 const rows=shop.data?.purchases??[];
 return <div className="data-panel"><div className="panel-heading"><h3>Sản phẩm đã mua</h3><div className="panel-actions"><Button size="sm" variant="outline" disabled={shop.busy||!rows.length} onClick={()=>onCopy(rows.map(r=>r.id))}><Copy size={13}/> Copy full</Button><Button size="sm" variant="outline" disabled={shop.busy||!rows.length} onClick={()=>onDownload(rows.map(r=>r.id))}><Download size={13}/> Xuất TXT</Button></div></div>{rows.map(r=><div className="digital-purchase" key={r.id}><div><strong>{r.name}</strong><small>{kindNames[r.kind]} · Đơn {r.order_id.slice(0,8)} · Dòng {r.position}</small></div><Button variant="outline" size="sm" disabled={shop.busy} onClick={()=>onCopy([r.id])}><Copy size={14}/> Lấy / copy</Button></div>)}{!rows.length&&<div className="empty-state"><Package/><h4>Chưa có sản phẩm được giao</h4><p>Sản phẩm xuất hiện sau khi đơn được duyệt.</p></div>}</div>;
}
