"use client";
import {useState,useEffect,useRef} from "react";
import {VietnamMap,vietnamCities} from "./vietnam-map";
import {ArrowRight,ArrowUpRight,ShieldCheck,Globe2,Copy,Wallet,Check,Layers3} from "lucide-react";
import {Button} from "./ui/button";
import type {Shop} from "./shop-dashboard";
export function GuestLanding({shop,onLogin,onRegister}:{shop:Shop;onLogin:()=>void;onRegister:()=>void}){
 const [activeCity,setActiveCity]=useState("hanoi");const root=useRef<HTMLElement>(null);
 useEffect(()=>{const element=root.current;if(!element||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const nodes=Array.from(element.querySelectorAll<HTMLElement>("[data-reveal]"));const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}},{threshold:.12,rootMargin:"0px 0px -35px 0px"});for(const node of nodes){if(node.getBoundingClientRect().top>=window.innerHeight){node.classList.add("reveal-ready");observer.observe(node);}}return()=>observer.disconnect();},[]);
 return <main ref={root} className="guest-landing"><section className="guest-hero section-width"><span className="guest-kicker"><i/> KẾT NỐI RIÊNG · QUẢN LÝ ĐƠN GIẢN</span><h1><span>ProxyVIP</span><br/>Kết nối ổn định.<br/><em>Làm việc liền mạch.</em></h1><p>Mua proxy, quản lý kết nối và nhận hỗ trợ trong một tài khoản. Kho được kiểm tra trước khi cấp, bảo hành giữ nguyên thời hạn.</p><div className="guest-actions"><Button size="lg" onClick={onRegister}>Bắt đầu với ProxyVIP <ArrowRight size={17}/></Button><Button size="lg" variant="outline" onClick={onLogin}>Đăng nhập</Button></div><div className="guest-trust"><span><ShieldCheck size={15}/> Bảo hành 30 ngày</span><span><Globe2 size={15}/> HTTP & SOCKS5</span><span><Copy size={15}/> Copy & xuất TXT</span></div></section>
 <section data-reveal className="guest-locations section-width"><div className="guest-section-title"><span className="guest-kicker">KHO KẾT NỐI</span><h2>Chọn kết nối<br/><em>phù hợp với bạn.</em></h2><p>Thông tin gói bán được cập nhật từ cửa hàng. Vị trí và tình trạng cụ thể sẽ hiển thị trong danh sách proxy sau khi được cấp.</p></div><div className="guest-location-grid"><div className="guest-map-card"><VietnamMap active={activeCity} onSelect={setActiveCity}/><div className="guest-map-caption"><div><strong>Hà Nội · Hải Phòng · Hồ Chí Minh</strong><span>Chọn thành phố để xem vị trí · minh họa địa điểm</span></div><Globe2 size={25}/></div></div><div className="guest-location-list">{vietnamCities.map(city=><button key={city.id} className={`guest-city-card ${activeCity===city.id?"selected":""}`} onClick={()=>setActiveCity(city.id)} aria-pressed={activeCity===city.id}><span className="guest-code">{city.code}</span><span className="guest-city-copy"><strong>{city.name}</strong><small>{city.caption}</small></span><span className="guest-tag">{activeCity===city.id?"Đang chọn":"Xem vị trí"}</span></button>)}{["ipv4","socks5"].map(code=>{const p=shop.data?.products.find(x=>x.code===code);return <article key={code}><span className="guest-code"><Layers3 size={23}/></span><div><h3>{code==="ipv4"?"HTTP / HTTPS":"SOCKS5"}</h3><p>{p?.enabled?p.price.toLocaleString("vi-VN")+" đ / proxy / 30 ngày":"Chưa mở bán"}</p></div><span className="guest-tag">{p?.enabled?"Mở bán":"Sắp có"}</span></article>})}<article><span className="guest-code"><ShieldCheck size={23}/></span><div><h3>Bảo hành 30 ngày</h3><p>Thay đúng dòng · giữ nguyên hạn dùng</p></div></article><article><span className="guest-code"><Wallet size={23}/></span><div><h3>Mua bằng số dư</h3><p>Nạp bằng QR · nhận hàng khi đủ kho</p></div></article><Button size="lg" onClick={onLogin}>Đăng nhập để chọn gói <ArrowRight size={17}/></Button></div></div></section>
 <section data-reveal className="guest-features section-width"><div className="guest-section-title"><span className="guest-kicker">MỌI THỨ TRONG MỘT TÀI KHOẢN</span><h2>Rõ ràng từ lúc mua<br/>đến khi sử dụng.</h2></div><div className="guest-feature-grid">{[{n:"01",title:"Chọn gói của bạn",text:"Đăng ký tài khoản, chọn giao thức và số lượng phù hợp."},{n:"02",title:"Nhận & quản lý",text:"Theo dõi danh sách được cấp, copy từng proxy hoặc xuất toàn bộ TXT."},{n:"03",title:"Hỗ trợ khi cần",text:"Theo dõi lịch sử bảo hành, liên hệ trực tiếp cửa hàng qua Zalo."}].map(x=><article key={x.n}><span>{x.n}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section><section data-reveal className="guest-final section-width"><div><span className="guest-kicker">SẴN SÀNG BẮT ĐẦU?</span><h2>Kết nối tiếp theo<br/>bắt đầu tại đây.</h2></div><div className="guest-actions"><Button size="lg" onClick={onRegister}>Tạo tài khoản <ArrowRight size={16}/></Button><Button asChild variant="outline" size="lg"><a href="https://zalo.me/0965003865" target="_blank" rel="noopener noreferrer">Hỗ trợ Zalo <ArrowUpRight size={16}/></a></Button></div></section><footer className="guest-footer section-width"><span className="footer-brand"><Layers3 size={20}/> proxyvip.</span><a href="https://zalo.me/0965003865" target="_blank" rel="noopener noreferrer">Zalo: 0965003865</a><span>© 2026 ProxyVIP · <strong className="design-credit">Design By Trumv</strong></span></footer></main>;
}

