"use client";
import {useState} from "react";
import type {Shop} from "./shop-dashboard";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
export function ManualTopup({shop,id,amount,onNotice}:{shop:Shop;id:string;amount:number;onNotice:(s:string)=>void}){
 const [open,setOpen]=useState(false),[reference,setReference]=useState(""),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false),[error,setError]=useState("");
 return <div className="wallet-form">{!open?<Button disabled={shop.preview} onClick={()=>setOpen(true)}>Duyệt và cộng tiền tay</Button>:<form className="wallet-form" onSubmit={async e=>{e.preventDefault();setError("");try{const r=await shop.action({action:"manual-topup",id,bankReference:reference,reason,confirmed});onNotice(r.message??"Đã cộng tiền.");setOpen(false);}catch(err){setError((err as Error).message);}}}><strong>Cộng {amount.toLocaleString("vi-VN")} đ vào ví khách</strong><label>Mã tham chiếu tại ngân hàng nhận<Input required minLength={4} maxLength={100} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Lấy từ lịch sử tiền vào MSB / SePay"/></label><label>Ghi chú đối soát<Input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ví dụ: đã nhận tiền, khách chuyển sai nội dung"/></label><label style={{display:"flex",alignItems:"start"}}><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Tôi đã kiểm tra tài khoản nhận và xác nhận đủ số tiền, đúng khách hàng.</label><p>Thao tác cộng tiền vào ví ngay và được ghi lại cùng người duyệt. Không duyệt chỉ dựa vào ảnh khách gửi.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="panel-actions"><Button disabled={shop.busy||shop.preview||!confirmed}>Xác nhận cộng {amount.toLocaleString("vi-VN")} đ</Button><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Hủy</Button></div></form>}</div>;
}
