"use client";
import {useEffect,useState} from "react";
import {Copy,Download,ExternalLink,RefreshCw} from "lucide-react";
import {Button} from "./ui/button";
import {bankApps} from "@/lib/bank-apps";
import {bankAppLink,paymentQr,type PaymentAccount} from "@/lib/payment-links";
export function PaymentTransfer({account,amount,code,onCopy,preview=false}:{account:PaymentAccount;amount:number;code:string;onCopy:(value:string)=>void;preview?:boolean}){
 const [platform,setPlatform]=useState<"android"|"ios"|"desktop">("desktop"),[appId,setAppId]=useState(""),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const ua=navigator.userAgent;setPlatform(/android/i.test(ua)?"android":/iPhone|iPad|iPod/i.test(ua)||navigator.maxTouchPoints>1&&/Macintosh/.test(ua)?"ios":"desktop");},[]);
 const qr=paymentQr(account,amount,code),download=paymentQr(account,amount,code,true),link=bankAppLink(appId,account,amount,code);
 const apps=bankApps.filter(app=>platform==="desktop"||app[platform]);
 if(!qr)return <p className="form-error">Chưa tạo được QR với thông tin tài khoản này. Bạn có thể chuyển thủ công theo mã nạp.</p>;
 return <div className="payment-transfer"><div className="payment-qr"><div className="payment-qr-frame">{failed?<div role="alert"><p>Chưa tải được ảnh QR.</p><Button size="sm" variant="outline" onClick={()=>{setFailed(false);setRetry(n=>n+1);}}><RefreshCw size={14}/> Tải lại QR</Button></div>:<img key={retry} src={qr} width={280} height={280} alt={`QR chuyển ${amount.toLocaleString("vi-VN")} đồng, nội dung ${code}`} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>}</div><a className="payment-link payment-link-secondary" href={download!} target="_blank" rel="noopener noreferrer"><Download size={15}/> Tải ảnh QR</a></div><div className="payment-transfer-details"><h4>Chuyển khoản bằng QR</h4><p>Quét bằng app ngân hàng. QR đã có số tiền và nội dung nạp.</p><dl><div><dt>Ngân hàng nhận</dt><dd>{account.bank}</dd></div><div><dt>Chủ tài khoản</dt><dd>{account.holder}</dd></div><div><dt>Số tài khoản</dt><dd>{account.number}<button aria-label="Copy số tài khoản" onClick={()=>onCopy(account.number)}><Copy size={14}/></button></dd></div><div><dt>Số tiền</dt><dd>{amount.toLocaleString("vi-VN")} đ<button aria-label="Copy số tiền" onClick={()=>onCopy(String(amount))}><Copy size={14}/></button></dd></div></dl><label>Ngân hàng bạn dùng để chuyển<select value={appId} onChange={e=>setAppId(e.target.value)}><option value="">Chọn ứng dụng ngân hàng</option>{apps.map(app=><option value={app.id} key={app.id}>{app.name}</option>)}</select></label>{link&&!preview?<a className="payment-link" href={link} rel="noreferrer"><ExternalLink size={15}/> Chuyển khoản · Mở app ngân hàng</a>:<Button disabled>Chuyển khoản · Mở app ngân hàng</Button>}<p className="muted">{platform==="desktop"?"Mở app hoạt động trên điện thoại đã cài ứng dụng. Trên máy tính, dùng điện thoại quét QR.":"Nếu app không điền sẵn thông tin, tải QR rồi chọn ảnh trong mục quét QR của app."} Kiểm tra người nhận, số tiền và giữ nguyên mã nạp trước khi xác nhận.</p></div></div>;
}
