"use client";
import {AuthDialog,logoutLocal} from "./auth-dialog";
import {customerView} from "@/lib/customer-view";
import {useState,useEffect,useRef} from "react";
import {ParticleBackground,ThemeToggle} from "@/components/site-effects";
import {DigitalCatalog} from "./digital-catalog";
import {useShop,ShopDashboard,ShopPurchase} from "@/components/shop-dashboard";
import {ArrowUpRight,ArrowRight,ShieldCheck,Zap,Globe2,Check,RefreshCw,Server,Activity,Menu,X,Clock3,CheckCircle2,Layers3,Terminal,LayoutDashboard} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
type View="home"|"proxies"|"history"|"inventory"|"catalog"|"purchases"|"orders"|"wallet";
const basePlans=[{name:"Proxy IPv4",tag:"LỰA CHỌN PHỔ BIẾN",description:"IP riêng, kết nối ổn định cho công việc hàng ngày.",price:"30.000",type:"HTTP / HTTPS",icon:Globe2},{name:"Proxy SOCKS5",tag:"LINH HOẠT KẾT NỐI",description:"Hỗ trợ nhiều ứng dụng và giao thức kết nối.",price:"35.000",type:"SOCKS5",icon:Layers3},{name:"Gói số lượng lớn",tag:"CHO ĐỘI NHÓM",description:"Quản lý tập trung, cấp proxy theo nhu cầu của bạn.",price:"Liên hệ",type:"HTTP / SOCKS5",icon:Server}];
export default function ProxySite(){
 const [authMode,setAuthMode]=useState<"login"|"register"|null>(null);useEffect(()=>{const value=new URLSearchParams(location.search).get("auth");if(value==="login"||value==="register")setAuthMode(value);},[]);
 const [topupDraft,setTopupDraft]=useState<string|null>(null);const originalShop=useShop();const [customerPreview,setCustomerPreview]=useState(false);
 const shop=customerPreview?{...originalShop,preview:true,exitPreview:(amount?:string)=>{if(amount)setTopupDraft(amount);setCustomerPreview(false);},data:customerView(originalShop.data),action:async(payload:Record<string,unknown>)=>{if(!["export","export-items"].includes(String(payload.action)))throw new Error("Đây là chế độ xem thử. Trở về quản trị để tạo hoặc xử lý đơn thử.");return originalShop.action(payload);}}:{...originalShop,topupDraft};
 const [view,setView]=useState<View>("home"),[mobile,setMobile]=useState(false),[help,setHelp]=useState(false),[purchase,setPurchase]=useState<string|null>(null),[notice,setNotice]=useState("");
 const previousUser=useRef<string|null>(null);useEffect(()=>{const email=originalShop.data?.user?.email??null;if(email&&email!==previousUser.current)setView("proxies");if(!email&&previousUser.current)setView("home");previousUser.current=email;},[originalShop.data?.user?.email]);
 const plans=basePlans.map((p,i)=>{const product=shop.data?.products.find(v=>v.code===(i===0?"ipv4":"socks5"));return {...p,enabled:i<2&&!!product?.enabled,priceLabel:i===2?"Liên hệ":product?.enabled?product.price.toLocaleString("vi-VN"):"Chưa mở bán"};});
 function navigate(v:View){setView(v);setMobile(false);window.scrollTo({top:0,behavior:"smooth"});}
 function choose(name:string){if(name==="Gói số lượng lớn"){setHelp(true);return;}setPurchase(name==="Proxy SOCKS5"?"socks5":"ipv4");}
 function pricing(){navigate("home");setTimeout(()=>document.getElementById("bang-gia")?.scrollIntoView({behavior:"smooth"}),0);}
 return <div className="site"><AuthDialog mode={authMode} setMode={setAuthMode} onDone={async()=>{await originalShop.reload();setView("proxies");setPurchase(null);}}/><ParticleBackground/><header className="header"><div className="header-inner"><button className="brand" onClick={()=>navigate("home")} aria-label="ProxyHub trang chủ"><span className="brand-symbol"><Layers3 size={22}/></span>proxy<span>hub</span><i/></button>{originalShop.data?.user&&<nav className="desktop-nav"><button className={view==="home"?"active":""} onClick={()=>navigate("home")}>Trang chủ</button><button onClick={pricing}>Bảng giá</button><button className={view!=="home"?"active":""} onClick={()=>navigate("proxies")}>Quản lý proxy</button><button onClick={()=>navigate("catalog")}>Sản phẩm khác</button><button onClick={()=>setHelp(true)}>Hướng dẫn <ArrowUpRight size={13}/></button></nav>}<div className="header-actions"><ThemeToggle/><div className="account-actions">{originalShop.data?.user?<Button variant="outline" onClick={async()=>{try{if(originalShop.data?.user?.authMethod!=="local"){location.assign("/signout-with-chatgpt?return_to=%2F");return;}await logoutLocal();await originalShop.reload();}catch(e){setNotice((e as Error).message);}}}>Đăng xuất</Button>:<><Button variant="outline" onClick={()=>setAuthMode("login")}>Đăng nhập</Button><Button variant="outline" onClick={()=>setAuthMode("register")}>Đăng ký</Button></>}</div><span className="service-status"><i/> Quản lý kết nối</span><button className="menu-button" aria-label="Mở menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></div>{mobile&&<nav className="mobile-nav">{originalShop.data?.user?<><button onClick={()=>navigate("home")}>Trang chủ</button><button onClick={pricing}>Bảng giá</button><button onClick={()=>navigate("proxies")}>Proxy của tôi</button><button onClick={()=>navigate("catalog")}>Sản phẩm khác</button><button onClick={async()=>{setMobile(false);try{if(originalShop.data?.user?.authMethod!=="local"){location.assign("/signout-with-chatgpt?return_to=%2F");return;}await logoutLocal();await originalShop.reload();}catch(e){setNotice((e as Error).message);}}}>Đăng xuất</button></>:<><button onClick={()=>{setAuthMode("login");setMobile(false);}}>Đăng nhập</button><button onClick={()=>{setAuthMode("register");setMobile(false);}}>Đăng ký</button></>}</nav>}</header>
 {originalShop.data?.user?.isAdmin&&<div className="customer-preview-bar section-width"><div><strong>{customerPreview?"Đang xem giao diện khách hàng":"Chế độ quản trị"}</strong>{customerPreview&&<span>Dữ liệu của tài khoản bạn · Xem thử, không tạo hoặc sửa đơn</span>}</div><Button variant="outline" size="sm" onClick={()=>{setCustomerPreview(v=>!v);setView("home");setPurchase(null);setNotice("");}}>{customerPreview?"Trở về quản trị":"Xem giao diện khách hàng"}</Button></div>}
 {view==="home"?<><main><section className="hero section-width"><div className="hero-copy"><div className="eyebrow"><span className="small-dot"/> KẾT NỐI ỔN ĐỊNH. CÔNG VIỆC LIỀN MẠCH.</div><h1><span className="hero-brand-accent">Proxy</span> cho mọi kết nối.<br/><span>An tâm mỗi ngày.</span></h1><p className="hero-description">Mua, quản lý và theo dõi proxy ở một nơi.<br className="desktop-only"/> Bảo hành 30 ngày, thay proxy lỗi ngay trong danh sách của bạn.</p><div className="hero-cta"><Button size="lg" onClick={pricing}>Khám phá các gói proxy <ArrowRight size={17}/></Button><Button size="lg" variant="outline" onClick={()=>navigate("proxies")}><LayoutDashboard size={17}/> Xem dashboard</Button></div><div className="hero-assurances"><span><ShieldCheck size={16}/> Bảo hành 30 ngày</span><span><CheckCircle2 size={16}/> HTTP & SOCKS5</span><span><Zap size={16}/> Thay thế tự động</span></div></div>
 <div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="preview-card"><div className="preview-top"><span className="preview-logo"><Layers3 size={17}/> proxyhub</span><span className="preview-sample">MINH HỌA</span><div className="window-dots"><i/><i/><i/></div></div><div className="preview-main"><div className="preview-heading"><div><small>TỔNG QUAN KẾT NỐI</small><h3>Proxy của bạn</h3></div><span className="refresh-bubble"><RefreshCw size={16}/></span></div><div className="preview-stats"><div><span>Proxy đang hoạt động</span><strong>24 <em>/ 25</em></strong><small><i/> Kết nối sẵn sàng</small></div><div><span>Đang được bảo hành</span><strong>100<em>%</em></strong><small><ShieldCheck size={12}/> 30 ngày an tâm</small></div></div><div className="preview-table"><div className="preview-labels"><span>ĐỊA CHỈ IP</span><span>GIAO THỨC</span><span>TRẠNG THÁI</span></div>{["192.0.2.14","192.0.2.28","192.0.2.36"].map((ip,i)=><div className="preview-row" key={ip}><span><Globe2 size={13}/>{ip}</span><span>{i===1?"SOCKS5":"HTTP"}</span><span className="live-badge"><i/> Live</span></div>)}</div><div className="preview-event"><span className="event-check"><Check size={14}/></span><div><strong>Đã thay thế proxy lỗi</strong><small>Danh sách cập nhật · Giữ nguyên hạn dùng</small></div><span>vừa xong</span></div></div></div><div className="floating-note"><span><ShieldCheck size={22}/></span><div><strong>Bảo hành tự động</strong><small>Bạn cứ tập trung vào công việc.</small></div><CheckCircle2 size={16}/></div></div></section>
 <div className="trust-bar"><div className="section-width"><span>MỘT NỀN TẢNG, ĐỦ MỌI NHU CẦU</span><strong><Globe2/> IP Việt Nam</strong><strong><ShieldCheck/> IP riêng biệt</strong><strong><Terminal/> HTTP / SOCKS5</strong><strong><RefreshCw/> Tự động bảo hành</strong></div></div>
 <section className="pricing section-width" id="bang-gia"><div className="section-heading"><div><span className="kicker">CHỌN KẾT NỐI CỦA BẠN</span><h2>Gói proxy phù hợp với bạn</h2><p>Đơn giản để bắt đầu. Dễ dàng mở rộng khi cần.</p></div><div className="billing-pill"><Clock3 size={15}/> Chu kỳ 30 ngày</div></div><p className="sample-price">Giá bán được cập nhật từ cửa hàng · Bảo hành 30 ngày từ lúc cấp proxy.</p><div className="plan-grid">{plans.map((p,i)=><article className={`plan-card ${i===0?"featured":""}`} key={p.name}><div className="plan-top"><span className="plan-icon"><p.icon size={23}/></span><span className="plan-tag">{p.tag}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="price">{p.priceLabel}<span>{i<2&&p.enabled?"đ / proxy / 30 ngày":""}</span></div><div className="plan-divider"/><ul>{[p.type,"Hỗ trợ IP Việt Nam","Bảo hành thay thế 30 ngày","Quản lý & xuất danh sách TXT"].map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul><Button variant={i===0?"default":"outline"} className="plan-button" onClick={()=>choose(p.name)}>{i===2?"Xem hướng dẫn":"Chọn gói này"}<ArrowRight size={16}/></Button></article>)}</div></section>
 <section className="warranty section-width"><div className="warranty-intro"><span className="kicker">BẢO HÀNH KHÔNG PHIỀN PHỨC</span><h2>Proxy lỗi?<br/>Danh sách tự cập nhật.</h2><p>Không cần thay từng dòng thủ công.<br/>Proxy mới thay đúng vị trí, giữ nguyên hạn dùng.</p><button onClick={()=>navigate("history")}>Xem lịch sử bảo hành <ArrowUpRight size={16}/></button></div><div className="warranty-steps">{[{icon:Activity,title:"Theo dõi kết nối",desc:"Kiểm tra tình trạng proxy trong danh sách của khách."},{icon:ShieldCheck,title:"Xác nhận & thay thế",desc:"Sau 3 lần lỗi liên tiếp, chọn proxy dự phòng đã kiểm tra live."},{icon:CheckCircle2,title:"Cập nhật ngay trong danh sách",desc:"Giữ nguyên thời hạn, lưu lịch sử để bạn dễ theo dõi."}].map((s,i)=><div className="warranty-step" key={s.title}><div className="step-icon"><s.icon size={20}/></div><div><small>0{i+1}</small><h3>{s.title}</h3><p>{s.desc}</p></div></div>)}</div></section>
 <div className="digital-home section-width"><DigitalCatalog shop={shop} onChoose={setPurchase} onNotice={setNotice}/></div><section className="bottom-cta section-width"><div><span className="kicker">SẴN SÀNG KẾT NỐI?</span><h2>Quản lý proxy, nhẹ nhàng hơn.</h2><p>Mọi địa chỉ, trạng thái và lịch sử trong một dashboard.</p></div><Button size="lg" onClick={()=>navigate("proxies")}>Mở dashboard <ArrowRight size={17}/></Button></section></main><footer className="footer section-width"><div><span className="footer-brand"><Layers3 size={20}/> proxyhub</span><p>Kết nối ổn định. Công việc liền mạch.</p></div><div><button onClick={()=>setHelp(true)}>Hướng dẫn sử dụng</button><button onClick={()=>setHelp(true)}>Chính sách bảo hành</button><a href="https://zalo.me/0965003865" target="_blank" rel="noopener noreferrer">Hỗ trợ Zalo: 0965003865</a><span>© 2026 ProxyHub · <strong className="design-credit">Design By Trumv</strong></span></div></footer></>:<ShopDashboard key={view} shop={shop} initialView={view} onBuy={()=>choose("Proxy IPv4")} onProduct={setPurchase} onNotice={setNotice}/> }
 <ShopPurchase shop={shop} code={purchase} close={()=>setPurchase(null)} onNotice={(s,delivered)=>{setNotice(s);navigate(delivered?(shop.data?.products.find(p=>p.code===purchase)?.kind==="PROXY"?"proxies":"purchases"):"orders");}}/>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="proxy-dialog"><DialogHeader><DialogTitle>Hướng dẫn & bảo hành</DialogTitle><DialogDescription>Mua và quản lý proxy tại ProxyHub.</DialogDescription></DialogHeader><div className="help-content"><h4>1. Chọn gói & tạo đơn</h4><p>Đăng nhập, chọn HTTP hoặc SOCKS5 và số lượng (tối đa 25 proxy mỗi đơn). Đơn chờ quản trị viên xác nhận thanh toán.</p><h4>2. Nhận proxy</h4><p>Hệ thống chỉ cấp proxy đã kiểm tra live. Trong dashboard, xuất TXT hoặc sao chép để lấy IP:port:user:pass đầy đủ. Bảo hành 30 ngày bắt đầu khi cấp.</p><h4>3. Thay thế tự động</h4><p>3 lần kiểm tra lỗi liên tiếp, cách nhau ít nhất 5 phút, mới xác nhận die. Proxy dự phòng cùng loại được kiểm tra live trước khi thay vào đúng dòng. Hạn dùng được giữ nguyên và lịch sử được lưu.</p><h4>4. Khi hết kho dự phòng</h4><p>Khách nhận thông báo trong dashboard; hệ thống tiếp tục thử khi có kho live. Nếu checker gặp lỗi mạng, việc đánh giá sẽ tạm dừng.</p><h4>Hỗ trợ khách hàng</h4><p>Liên hệ Zalo khi cần hỗ trợ đơn hàng hoặc bảo hành.</p><Button asChild><a href="https://zalo.me/0965003865" target="_blank" rel="noopener noreferrer">Zalo: 0965003865 <ArrowUpRight size={15}/></a></Button></div></DialogContent></Dialog>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button aria-label="Đóng thông báo" onClick={()=>setNotice("")}><X size={16}/></button></div>}</div>;
}

