"use client";
import {markLoginNotice} from "@/lib/login-notice";
import {Storefront} from "./storefront";
import {AuthDialog,logoutLocal} from "./auth-dialog";
import {customerView} from "@/lib/customer-view";
import {useState,useEffect,useRef} from "react";
import {ParticleBackground,ThemeToggle} from "@/components/site-effects";
import {DigitalCatalog} from "./digital-catalog";
import {useShop,ShopDashboard,ShopPurchase} from "@/components/shop-dashboard";
import {ShoppingBag,ArrowUpRight,ArrowRight,ShieldCheck,Zap,Globe2,Check,RefreshCw,Server,Activity,Menu,X,Clock3,CheckCircle2,Layers3,Terminal,LayoutDashboard} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
type View="home"|"proxies"|"history"|"inventory"|"catalog"|"purchases"|"orders"|"wallet";
const basePlans=[{name:"Proxy IPv4",tag:"LỰA CHỌN PHỔ BIẾN",description:"IP riêng, kết nối ổn định cho công việc hàng ngày.",price:"30.000",type:"HTTP / HTTPS",icon:Globe2},{name:"Proxy SOCKS5",tag:"LINH HOẠT KẾT NỐI",description:"Hỗ trợ nhiều ứng dụng và giao thức kết nối.",price:"35.000",type:"SOCKS5",icon:Layers3},{name:"Gói số lượng lớn",tag:"CHO ĐỘI NHÓM",description:"Quản lý tập trung, cấp proxy theo nhu cầu của bạn.",price:"Liên hệ",type:"HTTP / SOCKS5",icon:Server}];
export default function ProxySite(){
 const [authMode,setAuthMode]=useState<"login"|"register"|null>(null);useEffect(()=>{const value=new URLSearchParams(location.search).get("auth");if(value==="login"||value==="register")setAuthMode(value);},[]);
 const [loginNotices,setLoginNotices]=useState<import("./promotions-panel").Announcement[]>([]);const lastNoticeSession=useRef("");const [topupDraft,setTopupDraft]=useState<string|null>(null);const originalShop=useShop();const [customerPreview,setCustomerPreview]=useState(false);
 const shop=customerPreview?{...originalShop,preview:true,exitPreview:(amount?:string)=>{if(amount)setTopupDraft(amount);setCustomerPreview(false);},data:customerView(originalShop.data),action:async(payload:Record<string,unknown>)=>{if(!["export","export-items"].includes(String(payload.action)))throw new Error("Đây là chế độ xem thử. Trở về quản trị để tạo hoặc xử lý đơn thử.");return originalShop.action(payload);}}:{...originalShop,topupDraft};
 const [view,setView]=useState<View>("home"),[mobile,setMobile]=useState(false),[help,setHelp]=useState(false),[purchase,setPurchase]=useState<string|null>(null),[notice,setNotice]=useState("");
 const previousUser=useRef<string|null>(null);useEffect(()=>{const email=originalShop.data?.user?.email??null;if(email&&email!==previousUser.current)setView("catalog");if(!email&&previousUser.current)setView("home");previousUser.current=email;},[originalShop.data?.user?.email]);
 useEffect(()=>{const user=originalShop.data?.user;if(!user){setLoginNotices([]);lastNoticeSession.current="";return;}const notices=(originalShop.data?.announcements??[]).filter(n=>n.active);if(!notices.length||customerPreview)return;const session=user.noticeSession??"chatgpt:"+user.email;if(lastNoticeSession.current===session)return;try{if(!markLoginNotice(localStorage,user.email,session)){lastNoticeSession.current=session;return;}}catch{/* In-memory fallback when storage is blocked. */}lastNoticeSession.current=session;setLoginNotices(notices);},[originalShop.data?.user?.email,originalShop.data?.user?.noticeSession,originalShop.data?.announcements,customerPreview]);
 const plans=basePlans.map((p,i)=>{const product=shop.data?.products.find(v=>v.code===(i===0?"ipv4":"socks5"));return {...p,enabled:i<2&&!!product?.enabled,priceLabel:i===2?"Liên hệ":product?.enabled?product.price.toLocaleString("vi-VN"):"Chưa mở bán"};});
 function navigate(v:View){setView(v);setMobile(false);window.scrollTo({top:0,behavior:"smooth"});}
 function choose(name:string){if(name==="Gói số lượng lớn"){setHelp(true);return;}setPurchase(name==="Proxy SOCKS5"?"socks5":"ipv4");}
 function pricing(){navigate("home");setTimeout(()=>document.getElementById("store-products")?.scrollIntoView({behavior:"smooth"}),0);}
 return <div className="site"><AuthDialog mode={authMode} setMode={setAuthMode} onDone={async()=>{await originalShop.reload();setView("catalog");setPurchase(null);}}/><Dialog open={loginNotices.length>0} onOpenChange={open=>{if(!open)setLoginNotices([]);}}><DialogContent className="proxy-dialog"><DialogHeader><DialogTitle>Thông báo từ Tạp Hóa VIP</DialogTitle><DialogDescription>Thông báo mới nhất từ cửa hàng. Bạn có thể xem lại trong mục Thông báo.</DialogDescription></DialogHeader><div className="login-announcements">{loginNotices.map(n=><article className="announcement-card" key={n.id}><h4>{n.title}</h4><p>{n.message}</p><small>{new Date(n.created).toLocaleString("vi-VN")}</small></article>)}</div><Button onClick={()=>setLoginNotices([])}>Đã đọc</Button></DialogContent></Dialog><ParticleBackground/><header className="header"><div className="header-inner"><button className="brand" onClick={()=>navigate("home")} aria-label="Tạp Hóa VIP trang chủ"><span className="brand-symbol"><Layers3 size={22}/></span>taphoa<span>vip</span><i/></button>{originalShop.data?.user&&<nav className="desktop-nav"><button className={view==="home"?"active":""} onClick={()=>navigate("home")}>Cửa hàng</button><button onClick={pricing}>Danh mục</button><button className={view!=="home"?"active":""} onClick={()=>navigate("catalog")}>Dashboard</button><button onClick={()=>navigate("catalog")}>Sản phẩm số</button><button onClick={()=>setHelp(true)}>Hướng dẫn <ArrowUpRight size={13}/></button></nav>}<div className="header-actions"><ThemeToggle/><div className="account-actions">{originalShop.data?.user?<Button variant="outline" onClick={async()=>{try{if(originalShop.data?.user?.authMethod!=="local"){location.assign("/signout-with-chatgpt?return_to=%2F");return;}await logoutLocal();await originalShop.reload();}catch(e){setNotice((e as Error).message);}}}>Đăng xuất</Button>:<><Button variant="outline" onClick={()=>setAuthMode("login")}>Đăng nhập</Button><Button variant="outline" onClick={()=>setAuthMode("register")}>Đăng ký</Button></>}</div><span className="service-status"><i/> Sản phẩm số</span><button className="menu-button" aria-label="Mở menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></div>{mobile&&<nav className="mobile-nav">{originalShop.data?.user?<><button onClick={()=>navigate("home")}>Cửa hàng</button><button onClick={pricing}>Danh mục</button><button onClick={()=>navigate("proxies")}>Proxy của tôi</button><button onClick={()=>navigate("catalog")}>Sản phẩm số</button><button onClick={async()=>{setMobile(false);try{if(originalShop.data?.user?.authMethod!=="local"){location.assign("/signout-with-chatgpt?return_to=%2F");return;}await logoutLocal();await originalShop.reload();}catch(e){setNotice((e as Error).message);}}}>Đăng xuất</button></>:<><button onClick={()=>{setAuthMode("login");setMobile(false);}}>Đăng nhập</button><button onClick={()=>{setAuthMode("register");setMobile(false);}}>Đăng ký</button></>}</nav>}</header>
 {originalShop.data?.user?.isAdmin&&<div className="customer-preview-bar section-width"><div><strong>{customerPreview?"Đang xem giao diện khách hàng":"Chế độ quản trị"}</strong>{customerPreview&&<span>Dữ liệu của tài khoản bạn · Xem thử, không tạo hoặc sửa đơn</span>}</div><Button variant="outline" size="sm" onClick={()=>{setCustomerPreview(v=>!v);setView("home");setPurchase(null);setNotice("");}}>{customerPreview?"Trở về quản trị":"Xem giao diện khách hàng"}</Button></div>}
 {view==="home"?<Storefront shop={shop} onChoose={setPurchase} onLogin={()=>setAuthMode("login")} onRegister={()=>setAuthMode("register")}/>:<ShopDashboard key={view} shop={shop} initialView={view} onBuy={()=>navigate("home")} onProduct={setPurchase} onNotice={setNotice}/> }

 <ShopPurchase shop={shop} code={purchase} close={()=>setPurchase(null)} onNotice={(s,delivered)=>{setNotice(s);navigate(delivered?(shop.data?.products.find(p=>p.code===purchase)?.kind==="PROXY"?"proxies":"purchases"):"orders");}}/>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="proxy-dialog"><DialogHeader><DialogTitle>Hướng dẫn & bảo hành</DialogTitle><DialogDescription>Mua và quản lý proxy tại Tạp Hóa VIP.</DialogDescription></DialogHeader><div className="help-content"><h4>1. Chọn gói & tạo đơn</h4><p>Đăng nhập, chọn HTTP hoặc SOCKS5 và số lượng (tối đa 25 proxy mỗi đơn). Đơn chờ quản trị viên xác nhận thanh toán.</p><h4>2. Nhận proxy</h4><p>Hệ thống chỉ cấp proxy đã kiểm tra live. Trong dashboard, xuất TXT hoặc sao chép để lấy IP:port:user:pass đầy đủ. Bảo hành 30 ngày bắt đầu khi cấp.</p><h4>3. Thay thế tự động</h4><p>3 lần kiểm tra lỗi liên tiếp, cách nhau ít nhất 5 phút, mới xác nhận die. Proxy dự phòng cùng loại được kiểm tra live trước khi thay vào đúng dòng. Hạn dùng được giữ nguyên và lịch sử được lưu.</p><h4>4. Khi hết kho dự phòng</h4><p>Khách nhận thông báo trong dashboard; hệ thống tiếp tục thử khi có kho live. Nếu checker gặp lỗi mạng, việc đánh giá sẽ tạm dừng.</p><h4>Hỗ trợ khách hàng</h4><p>Liên hệ Zalo khi cần hỗ trợ đơn hàng hoặc bảo hành.</p><Button asChild><a href="https://zalo.me/0965003865" target="_blank" rel="noopener noreferrer">Zalo: 0965003865 <ArrowUpRight size={15}/></a></Button></div></DialogContent></Dialog>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button aria-label="Đóng thông báo" onClick={()=>setNotice("")}><X size={16}/></button></div>}</div>;
}
