"use client";
import {useState} from "react";
import type {Shop} from "./shop-dashboard";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import {Textarea} from "./ui/textarea";
import {MoneyField} from "./money-field";
import {moneyValue} from "@/lib/money-input";
const money=(n:number)=>n.toLocaleString("vi-VN")+" đ";
const kinds={PROXY:"Proxy",ACCOUNT:"Tài khoản",KEY:"Mã key",TEXT:"Text",LINK:"Link",FILE_LINK:"Link tải file"};
export function SellerPanel({shop,onNotice,onCopy}:{shop:Shop;onNotice:(text:string)=>void;onCopy:(text:string)=>void}){
 const admin=!!shop.data?.user?.isAdmin,data=shop.data?.seller;
 const [email,setEmail]=useState(""),[invite,setInvite]=useState(""),[error,setError]=useState(""),[token,setToken]=useState(""),[reviewNotes,setReviewNotes]=useState<Record<string,string>>({}),[draft,setDraft]=useState<{code:string;name:string;kind:string;protocol:string;price:string;description:string}|null>(null),[importCode,setImportCode]=useState(""),[stock,setStock]=useState("");
 async function run(payload:Record<string,unknown>){setError("");try{const r=await shop.action(payload);onNotice(r.message??"Đã lưu.");return r;}catch(e){setError((e as Error).message);return null;}}
 return <section className="seller-panel"><div className="data-panel wallet-form"><h3>{admin?"CTV và kiểm duyệt sản phẩm":"Gian hàng CTV"}</h3><p>Phí nền tảng 5% mỗi sản phẩm bán thành công, làm tròn đến đồng. Phần còn lại được ghi vào doanh thu CTV để đối soát.</p>{error&&<p role="alert" className="form-error">{error}</p>}{admin?<><label>Email người được cấp quyền<Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button disabled={shop.busy||!email.trim()} onClick={async()=>{const r=await run({action:"seller-invite",email});if(r?.invite)setInvite(r.invite);}}>Tạo mã mời CTV</Button>{invite&&<label>Mã mời · gửi riêng cho CTV<Input readOnly value={invite}/><Button variant="outline" onClick={()=>onCopy(invite)}>Copy mã mời</Button></label>}{data?.members.map(m=><div className="seller-member" key={m.customer_id}><span>{m.name} · {m.email} · {m.active?"Đang có quyền":"Đã khóa"}</span><Button size="sm" variant="outline" disabled={shop.busy} onClick={()=>void run({action:"seller-status",id:m.customer_id,active:!m.active})}>{m.active?"Khóa quyền":"Mở lại quyền"}</Button></div>)}</>:!data?.membership?.active?<><p>Nhập mã mời do chủ cửa hàng cấp để đăng sản phẩm và nhập kho riêng.</p><Input aria-label="Mã mời CTV" value={token} onChange={e=>setToken(e.target.value.trim())}/><Button disabled={shop.busy||!token} onClick={async()=>{const r=await run({action:"seller-accept",token});if(r)setToken("");}}>Nhận quyền CTV</Button></>:<Button onClick={()=>setDraft({code:"",name:"",kind:"ACCOUNT",protocol:"HTTP",price:"",description:""})}>Thêm sản phẩm để duyệt</Button>}</div>
 {draft&&<form className="data-panel wallet-form" onSubmit={async e=>{e.preventDefault();const r=await run({action:"seller-save",...draft,price:moneyValue(draft.price)});if(r)setDraft(null);}}><h3>{draft.code?"Sửa và gửi duyệt lại":"Sản phẩm mới"}</h3><label>Tên sản phẩm<Input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Loại sản phẩm<select disabled={!!draft.code} value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{Object.entries(kinds).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{draft.kind==="PROXY"&&<label>Giao thức<select disabled={!!draft.code} value={draft.protocol} onChange={e=>setDraft({...draft,protocol:e.target.value})}><option>HTTP</option><option>SOCKS5</option></select></label>}<label>Giá bán mỗi sản phẩm<MoneyField value={draft.price} onChange={price=>setDraft({...draft,price})}/></label><small>Phí 5%: {money(Math.round((moneyValue(draft.price)??0)*0.05))} / sản phẩm</small><label>Mô tả<Textarea maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="panel-actions"><Button disabled={shop.busy||!(moneyValue(draft.price)??0)} type="submit">Gửi duyệt</Button><Button type="button" variant="outline" onClick={()=>setDraft(null)}>Đóng</Button></div></form>}
 <div className="digital-grid">{data?.products.map(p=><article className="data-panel digital-card" key={p.code}><span className="protocol-badge">{kinds[p.kind as keyof typeof kinds]}</span><h3>{p.name}</h3>{admin&&<small>CTV: {p.seller_email}</small>}<p>{p.description}</p><strong>{money(p.price)} / sản phẩm</strong><small>Kho còn {p.available} · {p.review_state==="APPROVED"?p.enabled?"Đang bán":"Tạm tắt":p.review_state==="PENDING"?"Chờ duyệt":"Bị từ chối"}</small>{p.review_note&&<p>Lý do: {p.review_note}</p>}{admin?<><Textarea aria-label={`Ghi chú duyệt ${p.name}`} placeholder="Ghi chú hoặc lý do từ chối" value={reviewNotes[p.code]??""} onChange={e=>setReviewNotes({...reviewNotes,[p.code]:e.target.value})}/><div className="panel-actions"><Button size="sm" disabled={shop.busy} onClick={()=>void run({action:"seller-review",code:p.code,approve:true,note:reviewNotes[p.code]??""})}>Duyệt mở bán</Button><Button variant="outline" size="sm" disabled={shop.busy} onClick={()=>void run({action:"seller-review",code:p.code,approve:false,note:reviewNotes[p.code]??""})}>Từ chối / tắt</Button></div></>:data?.membership?.active&&<div className="panel-actions"><Button size="sm" variant="outline" onClick={()=>setDraft({code:p.code,name:p.name,kind:p.kind,protocol:p.protocol,price:String(p.price),description:p.description})}>Sửa / gửi lại</Button><Button size="sm" onClick={()=>{setImportCode(p.code);setStock("");}}>Nhập kho riêng</Button></div>}</article>)}</div>
 {importCode&&<div className="data-panel wallet-form"><h3>Nhập kho riêng</h3><Textarea rows={7} value={stock} onChange={e=>setStock(e.target.value)} placeholder="Một sản phẩm mỗi dòng. Proxy: IP:port:user:pass"/><label>Nhập file TXT<Input type="file" accept=".txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>200000){setError("File tối đa 200 KB.");return;}setStock(await f.text());}}/></label><div className="panel-actions"><Button disabled={shop.busy||!stock.trim()} onClick={async()=>{if(await run({action:"seller-import",product:importCode,text:stock})){setImportCode("");setStock("");}}}>Nhập kho</Button><Button variant="outline" onClick={()=>{setImportCode("");setStock("");}}>Đóng</Button></div></div>}
 <div className="data-panel wallet-form"><h3>Doanh thu CTV sau phí</h3><strong>{money(data?.totals?.net??0)}</strong>{data?.sales.map(s=><div className="wallet-ledger" key={s.order_id}><div><strong>{s.product_name} · {s.quantity} sản phẩm</strong><small>Đơn {s.order_id.slice(0,8)} · Tổng {money(s.gross)} · Phí {money(s.fee)}</small></div><strong>{money(s.net)}</strong></div>)}{!data?.sales.length&&<p>Chưa có sản phẩm bán thành công.</p>}</div></section>;
}
