"use client";
import {useEffect,useRef,useState} from "react";
import type {Shop} from "./shop-dashboard";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Wallet,RefreshCw,Copy,CheckCircle2} from "lucide-react";
import {PaymentTransfer} from "./payment-transfer";
const money=(n:number)=>n.toLocaleString("vi-VN")+" đ",date=(n:number)=>new Date(n).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"});
const statuses:Record<string,string>={PENDING:"Chờ tiền",CREDITED:"Đã cộng",REVIEW:"Cần đối soát"};
export function WalletPanel({shop,onNotice,onCopy,preview=false}:{shop:Shop;onNotice:(text:string)=>void;onCopy:(text:string)=>void;preview?:boolean}){
 const [amount,setAmount]=useState(shop.topupDraft??"10000"),[error,setError]=useState("");const requestId=useRef(crypto.randomUUID());
 const wallet=shop.data?.wallet,pending=wallet?.topups.find(t=>t.status==="PENDING"),id=pending?.id,action=shop.action;
 useEffect(()=>{if(!id||preview||!wallet?.sepay.enabled)return;const timer=setInterval(()=>{if(!document.hidden)void action({action:"check-topup",id}).catch(e=>setError((e as Error).message));},30000);return()=>clearInterval(timer);},[id,preview,wallet?.sepay.enabled,action]);
 async function check(id:string){setError("");try{const r=await action({action:"check-topup",id});onNotice(r.message??"Đã kiểm tra.");}catch(e){setError((e as Error).message);}}
 return <section className="wallet-panel"><div className="wallet-balance data-panel"><Wallet size={24}/><div><span>Số dư của bạn</span><strong>{money(wallet?.balance??0)}</strong></div><Button variant="outline" size="sm" onClick={()=>void shop.reload()}><RefreshCw size={14}/> Làm mới</Button></div>
 <div className="wallet-summary">{[{label:"Tổng đã nạp",amount:wallet?.totals?.deposited??0},{label:"Đã mua bằng ví",amount:wallet?.totals?.spent??0},{label:"Còn lại",amount:wallet?.balance??0}].map(x=><div className="data-panel" key={x.label}><span>{x.label}</span><strong>{money(x.amount)}</strong></div>)}</div><p className="muted">Thống kê ví của bạn từ trước đến nay; chỉ tính khoản nạp đã cộng thành công.</p>
 <div className="data-panel wallet-form"><h3>Nạp tiền tự động</h3>{preview&&<p className="dashboard-tip">Bạn đang xem thử khách hàng. Trở về tài khoản của bạn để tạo QR và nạp tiền thật.</p>}{wallet?.sepay.enabled?<><p>{wallet.sepay.bank} · {wallet.sepay.accountNumber}<br/>{wallet.sepay.holder}</p><label>Số tiền muốn nạp (đ)<Input inputMode="numeric" value={amount} onChange={e=>{if(/^\d*$/.test(e.target.value))setAmount(e.target.value);}}/></label><Button disabled={shop.busy||(preview?!shop.exitPreview:Number(amount)<1000||Number(amount)>100000000)} onClick={async()=>{if(preview){shop.exitPreview?.(amount);return;}setError("");try{const r=await action({action:"create-topup",amount:Number(amount),requestId:requestId.current});onNotice(r.message??"Đã tạo yêu cầu nạp.");requestId.current=crypto.randomUUID();}catch(e){setError((e as Error).message);}}}>{shop.busy?"Đang xử lý...":preview?"Trở về tài khoản để nạp":"Tạo QR nạp tiền"}</Button><p className="muted">Tạo mã rồi chuyển đúng số tiền và nội dung. Kiểm tra mỗi 30 giây khi mở ví; lịch nền mỗi giờ. Mã quá 24 giờ hoặc chuyển sai số tiền sẽ cần đối soát.</p></>:<p>Nạp tiền tự động chưa được cấu hình. Bạn vẫn có thể mua theo hình thức xác nhận chuyển khoản thủ công.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{!wallet?.topups.some(t=>t.status!=="CREDITED")&&<p>Chưa có yêu cầu nạp đang chờ.</p>}{wallet?.topups.filter(t=>t.status!=="CREDITED").map(t=><article className="topup-card" key={t.id}><div><strong>{money(t.amount)}</strong><span className={`status-badge ${t.status==="CREDITED"?"live":"waiting"}`}>{statuses[t.status]}</span></div><label>Nội dung chuyển khoản<Input readOnly value={t.code} onFocus={e=>e.target.select()}/></label><div className="panel-actions"><Button size="sm" variant="outline" onClick={()=>onCopy(t.code)}><Copy size={13}/> Copy mã</Button>{t.status==="PENDING"&&<Button size="sm" disabled={shop.busy||preview} onClick={()=>void check(t.id)}><RefreshCw size={13}/> Kiểm tra tiền</Button>}</div><>{t.payment&&<PaymentTransfer account={t.payment} amount={t.amount} code={t.code} onCopy={onCopy} preview={preview}/>}</>{t.status==="PENDING"&&<div className="transfer-confirm"><Button disabled={shop.busy||preview} onClick={()=>void check(t.id)}><CheckCircle2 size={17}/>{shop.busy?"Đang xác minh giao dịch...":"Tôi đã chuyển khoản"}</Button><p className="muted">Bấm sau khi chuyển đúng số tiền và nội dung. Số dư chỉ được cộng khi hệ thống xác minh giao dịch thành công.</p></div>}<small>{date(t.created)} · {t.status==="CREDITED"?"Tiền đã vào ví":"Hạn đối soát: "+date(t.expires)}</small>{t.note&&<p>{t.note}</p>}</article>)}</div>
 <section className="data-panel wallet-form"><h3>Lịch sử nạp tiền</h3><p className="muted">50 yêu cầu nạp gần nhất. Chờ tiền / cần đối soát chưa được cộng vào số dư.</p>{!wallet?.topups.length&&<p>Chưa có lịch sử nạp.</p>}{wallet?.topups.map(t=><div className="wallet-ledger" key={t.id}><div><strong>{money(t.amount)}</strong><small>{date(t.created)} · {t.code}</small></div><span className={`status-badge ${t.status==="CREDITED"?"live":"waiting"}`}>{statuses[t.status]}</span></div>)}</section>
 {shop.data?.user?.isAdmin&&wallet?.adminTotals&&<section className="data-panel wallet-form"><h3>Tổng quan ví khách hàng</h3><div className="wallet-summary">{[{label:"Tổng nạp đã cộng",amount:wallet.adminTotals.deposited},{label:"Tổng mua bằng ví",amount:wallet.adminTotals.spent},{label:"Tổng số dư còn lại",amount:wallet.adminTotals.balance}].map(x=><div className="data-panel" key={x.label}><span>{x.label}</span><strong>{money(x.amount)}</strong></div>)}</div><h4>100 khoản nạp thành công gần nhất</h4>{!wallet.adminDeposits?.length&&<p>Chưa có khoản nạp thành công.</p>}{wallet.adminDeposits?.map(d=><div className="wallet-ledger" key={d.id}><div><strong>{d.email}</strong><small>{date(d.created)}</small></div><strong className="wallet-credit">+{money(d.amount)}</strong></div>)}</section>}
 <div className="data-panel wallet-form"><h3>Lịch sử số dư</h3>{!wallet?.ledger.length&&<p>Chưa có giao dịch số dư.</p>}{wallet?.ledger.map(l=><div className="wallet-ledger" key={l.id}><div><strong>{l.kind==="TOPUP"?"Nạp tiền tự động":"Mua hàng"}</strong><small>{date(l.created)}</small></div><strong className={l.amount>0?"wallet-credit":""}>{l.amount>0?"+":""}{money(l.amount)}</strong></div>)}</div></section>;
}
export function SePaySettings({shop,onNotice}:{shop:Shop;onNotice:(text:string)=>void}){
 const [banks,setBanks]=useState<{id:string;number:string;holder:string;bank:string}[]>([]);
 const c=shop.data?.wallet?.sepay;const [bankId,setBankId]=useState<string|null>(null),[token,setToken]=useState(""),[error,setError]=useState("");
 async function save(enabled:boolean){setError("");try{const r=await shop.action({action:"sepay-settings",enabled,bankId:bankId??c?.bankId??"",token});onNotice(r.message??"Đã lưu.");setToken("");}catch(e){setError((e as Error).message);}}
 return <div className="data-panel wallet-form"><h3>SePay · Nạp tiền và số dư</h3><p>{c?.enabled?`Đang bật: ${c.bank} · ${c.accountNumber} · ${c.holder}`:"Chưa bật SePay"}</p><label>UUID tài khoản ngân hàng trong SePay<Input value={bankId??c?.bankId??""} onChange={e=>setBankId(e.target.value)}/></label><label>API Token SePay<Input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={c?.hasToken?"Để trống để giữ token hiện tại":"Nhập token Production"}/></label><Button variant="outline" disabled={shop.busy} onClick={async()=>{setError("");try{const r=await shop.action({action:"sepay-banks",token});setBanks(r.banks??[]);onNotice(r.message??"Đã tải ngân hàng.");}catch(e){setError((e as Error).message);}}}>Tải danh sách ngân hàng</Button>{banks.length>0&&<label>Chọn ngân hàng nhận tiền<select value={bankId??c?.bankId??""} onChange={e=>setBankId(e.target.value)}><option value="">Chọn tài khoản...</option>{banks.map(b=><option key={b.id} value={b.id}>{b.bank} · {b.number} · {b.holder}</option>)}</select></label>}<p className="muted">Token được mã hóa phía máy chủ. Khi bật, web kiểm tra ngân hàng từ API SePay và lấy số tài khoản, chủ tài khoản. Hiện dùng API Production; không dùng token Test mode.</p><div className="panel-actions"><Button disabled={shop.busy} onClick={()=>void save(true)}>Kiểm tra và bật SePay</Button><Button variant="outline" disabled={shop.busy||!c?.enabled} onClick={()=>void save(false)}>Tắt nạp SePay</Button></div>{error&&<p className="form-error" role="alert">{error}</p>}<p className="muted">Khi có số dư, khách có thể mua và nhận hàng ngay; hàng hết kho hoặc cấp lỗi thì không trừ tiền. Đối soát API khi khách mở ví / bấm kiểm tra, và mỗi giờ khi web đóng. Web vẫn giữ riêng, chưa có webhook nhận tiền tức thời.</p>
 {!!shop.data?.wallet?.review.length&&<><h4>Yêu cầu cần đối soát</h4>{shop.data.wallet.review.map(t=><article className="topup-card" key={t.id}><strong>{t.email} · {money(t.amount)}</strong><code>{t.code}</code><p>{t.note}</p><small>Đối chiếu trong SePay trước khi xử lý; chưa tự cộng tiền.</small></article>)}</>}
 </div>;
}

