import {ShopError,quantity} from "./proxy-rules";
export type Coupon={code:string;kind:string;value:number;min_total:number;max_discount:number;product:string|null;expires:number;max_uses:number;enabled:number;created:number};
export function couponCode(input:unknown){if(input==null||input==="")return "";if(typeof input!=="string")throw new ShopError("Mã giảm giá không hợp lệ.");const code=input.trim().toUpperCase();if(!/^[A-Z0-9_-]{3,32}$/.test(code))throw new ShopError("Mã giảm giá gồm 3–32 ký tự chữ, số, _ hoặc -.");return code;}
export async function promotionSnapshot(db:D1Database,isAdmin:boolean){const announcements=(await db.prepare("SELECT * FROM announcements "+(isAdmin?"":"WHERE active=1 ")+"ORDER BY created DESC LIMIT 50").all()).results;const coupons=isAdmin?(await db.prepare("SELECT c.*,(SELECT COUNT(*) FROM coupon_uses u JOIN orders o ON o.id=u.order_id WHERE u.code=c.code AND o.status<>'CANCELLED') used FROM coupons c ORDER BY created DESC LIMIT 100").all()).results:[];return {announcements,coupons};}
export async function couponQuote(db:D1Database,customerId:string,product:{code:string;price:number;seller_id?:string|null},count:number,input:unknown){const code=couponCode(input),subtotal=product.price*count;if(!code)return {code:"",subtotal,discount:0,total:subtotal};if(product.seller_id)throw new ShopError("Mã cửa hàng chưa áp dụng cho sản phẩm của CTV.");const c=await db.prepare("SELECT * FROM coupons WHERE code=?").bind(code).first<Coupon>();if(!c||!c.enabled||c.expires<=Date.now()||c.product&&c.product!==product.code)throw new ShopError("Mã không còn hiệu lực hoặc không áp dụng cho sản phẩm này.");if(subtotal<c.min_total)throw new ShopError(`Đơn cần từ ${c.min_total.toLocaleString("vi-VN")} đ để dùng mã.`);const used=await db.prepare("SELECT COUNT(*) n,COALESCE(SUM(CASE WHEN u.customer_id=? THEN 1 ELSE 0 END),0) own FROM coupon_uses u JOIN orders o ON o.id=u.order_id WHERE u.code=? AND o.status<>'CANCELLED'").bind(customerId,code).first<{n:number;own:number}>();if((used?.n??0)>=c.max_uses)throw new ShopError("Mã đã hết lượt sử dụng.");if(used?.own)throw new ShopError("Mỗi tài khoản chỉ dùng mã này một lần. Kiểm tra đơn đang chờ.");let discount=c.kind==="PERCENT"?Math.floor(subtotal*c.value/100):c.value;if(c.max_discount)discount=Math.min(discount,c.max_discount);discount=Math.min(discount,Math.max(0,subtotal-1));return {code,subtotal,discount,total:subtotal-discount};}
export function couponReservation(db:D1Database,orderId:string,customerId:string,code:string){if(!code)return [];return [db.prepare("INSERT INTO coupon_uses(order_id,code,customer_id,created) VALUES(?,?,?,?)").bind(orderId,code,customerId,Date.now())];}
export async function promotionAction(db:D1Database,user:{userId:string;isAdmin:boolean},payload:Record<string,unknown>){const action=String(payload.action);if(action==="coupon-quote"){const product=await db.prepare("SELECT code,price,seller_id FROM products WHERE code=? AND enabled=1 AND (seller_id IS NULL OR review_state='APPROVED')").bind(String(payload.product)).first<{code:string;price:number;seller_id:string|null}>();if(!product)throw new ShopError("Sản phẩm chưa mở bán.");return {...await couponQuote(db,user.userId,product,quantity(payload.quantity),payload.coupon),message:"Đã áp dụng mã giảm giá."};}if(!user.isAdmin)throw new ShopError("Chỉ quản trị viên được thao tác.",403);
 if(action==="announcement-publish"){const title=String(payload.title??"").trim(),message=String(payload.message??"").trim();if(title.length<3||title.length>120||message.length<3||message.length>3000)throw new ShopError("Tiêu đề 3–120 ký tự, nội dung 3–3.000 ký tự.");const id=String(payload.id??"");if(!/^[a-f0-9-]{36}$/.test(id))throw new ShopError("Mã thông báo không hợp lệ.");await db.prepare("INSERT INTO announcements(id,title,message,created) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(id,title,message,Date.now()).run();return {message:"Đã phát hành thông báo cho khách."};}
 if(action==="announcement-toggle"){if(typeof payload.active!=="boolean")throw new ShopError("Trạng thái không hợp lệ.");await db.prepare("UPDATE announcements SET active=? WHERE id=?").bind(payload.active?1:0,String(payload.id)).run();return {message:payload.active?"Đã hiện thông báo.":"Đã ẩn thông báo."};}
 if(action==="coupon-publish"){const code=couponCode(payload.code),kind=String(payload.kind),value=Number(payload.value),min=Number(payload.minTotal??0),cap=Number(payload.maxDiscount??0),expires=Number(payload.expires),uses=Number(payload.maxUses),product=payload.product?String(payload.product):null;if(!code||!["PERCENT","AMOUNT"].includes(kind)||!Number.isSafeInteger(value)||value<1||value>(kind==="PERCENT"?99:100000000)||![min,cap].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=100000000)||!Number.isSafeInteger(uses)||uses<1||uses>100000||!Number.isSafeInteger(expires)||expires<=Date.now())throw new ShopError("Kiểm tra mức giảm, hạn dùng và số lượt.");if(product&&!await db.prepare("SELECT code FROM products WHERE code=? AND seller_id IS NULL").bind(product).first())throw new ShopError("Chọn sản phẩm của cửa hàng.");if(await db.prepare("SELECT code FROM coupons WHERE code=?").bind(code).first())throw new ShopError("Mã đã tồn tại. Dùng mã khác.",409);await db.prepare("INSERT INTO coupons(code,kind,value,min_total,max_discount,product,expires,max_uses,created) VALUES(?,?,?,?,?,?,?,?,?)").bind(code,kind,value,min,cap,product,expires,uses,Date.now()).run();return {message:"Đã phát hành mã giảm giá."};}
 if(action==="coupon-toggle"){if(typeof payload.enabled!=="boolean")throw new ShopError("Trạng thái không hợp lệ.");await db.prepare("UPDATE coupons SET enabled=? WHERE code=?").bind(payload.enabled?1:0,couponCode(payload.code)).run();return {message:payload.enabled?"Đã bật mã.":"Đã ngừng phát hành mã."};}throw new ShopError("Thao tác không hợp lệ.");}

