import {promotionSnapshot,promotionAction,couponQuote,couponReservation,couponCode} from "./promotions";
import {env} from "cloudflare:workers";
import {getChatGPTUser} from "@/app/chatgpt-auth";
import {ShopError,parseProxyLines,quantity,WARRANTY_MS,MIN_CHECK_INTERVAL,canReplace,healthAfter} from "./proxy-rules";
import {encryptCredentials,decryptCredentials,fingerprint} from "./proxy-crypto";
import {walletSnapshot,walletAction,walletBalance,walletDebit,syncSePay} from "./wallet";
import {digitalSnapshot,digitalAction,approveDigital} from "./digital-products";
import {checkProxy} from "./proxy-checker";
import {localIdentity} from "./local-auth";
import {sellerSnapshot,sellerAction,saleStatements,sellerFee} from "./seller-service";

type ShopEnv={DB?:D1Database;PROXY_ENCRYPTION_KEY?:string;ADMIN_EMAIL?:string};
type Stock={id:string;host:string;port:number;protocol:string;credentials:string;region:string;state:string;health:string;failures:number;checked:number;latency:number|null;provider_expiry:number|null};
type Order={id:string;customer_id:string;product:string;quantity:number;total:number;status:string;payment_method:string;coupon_code:string;discount:number;seller_id:string|null;unit_fee:number;unit_price:number};
const plans=[{code:"ipv4",name:"Proxy IPv4",protocol:"HTTP"},{code:"socks5",name:"Proxy SOCKS5",protocol:"SOCKS5"}];
const runtime=()=>env as unknown as ShopEnv;
function database(){const db=runtime().DB;if(!db)throw new ShopError("Kho dữ liệu chưa sẵn sàng. Vui lòng thử lại sau.",503);return db;}
function secret(){const key=runtime().PROXY_ENCRYPTION_KEY;if(!key)throw new ShopError("Chưa cấu hình khóa bảo vệ proxy.",503);return key;}
function sql(query:string,...values:unknown[]){return database().prepare(query).bind(...values);}
async function all<T>(query:string,...values:unknown[]){return (await sql(query,...values).all<T>()).results;}
async function identity(request?:Request){const local=await localIdentity(database(),request);if(local)return {...local,authMethod:"local"};const user=await getChatGPTUser();return user?{...user,isAdmin:user.email.toLowerCase()===runtime().ADMIN_EMAIL?.toLowerCase(),authMethod:"chatgpt"}:null;}
async function register(user:NonNullable<Awaited<ReturnType<typeof identity>>>){await sql("INSERT INTO customers(id,email,name,created) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name",user.userId,user.email,user.displayName,Date.now()).run();}
async function baseline(){try{const r=await fetch("https://www.gstatic.com/generate_204",{signal:AbortSignal.timeout(8000),cache:"no-store"});if(r.status!==204)throw new Error();}catch{throw new ShopError("Đích kiểm tra hoặc mạng của checker đang lỗi. Chưa kết luận proxy die.",503);}}
async function locked<T>(work:(assert:()=>Promise<void>)=>Promise<T>){const owner=crypto.randomUUID(),expires=Date.now()+120000;await sql("INSERT INTO locks(id,owner,expires) VALUES('inventory',?,?) ON CONFLICT(id) DO UPDATE SET owner=excluded.owner,expires=excluded.expires WHERE locks.expires < ?",owner,expires,Date.now()).run();const lock=await sql("SELECT owner FROM locks WHERE id='inventory'").first<{owner:string}>();if(lock?.owner!==owner)throw new ShopError("Kho đang xử lý một yêu cầu khác. Thử lại sau vài giây.",409);const assert=async()=>{const row=await sql("SELECT owner,expires FROM locks WHERE id='inventory'").first<{owner:string;expires:number}>();if(row?.owner!==owner||row.expires<Date.now()+3000)throw new ShopError("Phiên xử lý hết hạn. Vui lòng thử lại.",409);};try{return await work(assert);}finally{await sql("DELETE FROM locks WHERE id='inventory' AND owner=?",owner).run();}}
async function probe(stock:Stock,force=false){const now=Date.now();if(!force&&now-stock.checked<MIN_CHECK_INTERVAL)return stock.health==="LIVE";const credentials=await decryptCredentials(stock.credentials,secret());const result=await checkProxy({...stock,...credentials});const next=healthAfter(stock,result.ok,Date.now());if(next.accepted||result.ok||result.unsupported||force){const health=result.unsupported?"BLOCKED":result.ok?"LIVE":next.count>=3?"DEAD":"SUSPECT";await sql("UPDATE stock SET health=?,failures=?,checked=?,latency=?,last_error=? WHERE id=?",health,result.unsupported?stock.failures:next.count,Date.now(),result.latency,result.error,stock.id).run();}return result.ok;}
async function candidates(protocol:string,expires:number,limit:number,product:string|null=null){return all<Stock>("SELECT * FROM stock WHERE archived=0 AND state='AVAILABLE' AND protocol=? AND ((? IS NULL AND product IS NULL) OR product=?) AND (provider_expiry IS NULL OR provider_expiry>=?) AND health IN ('LIVE','UNKNOWN','SUSPECT') ORDER BY CASE WHEN health='LIVE' THEN 0 ELSE 1 END,checked DESC LIMIT ?",protocol,product,product,expires,limit);}
async function verified(pool:Stock[],needed:number){const result:Stock[]=[];for(let i=0;i<pool.length&&result.length<needed;i+=4){const group=pool.slice(i,i+4);const ok=await Promise.all(group.map(p=>probe(p,true)));for(let j=0;j<group.length&&result.length<needed;j++)if(ok[j])result.push(group[j]);}return result;}
function transactionGuard(id:string,query:string,...args:unknown[]){return sql(`INSERT INTO transaction_guards(id,valid) SELECT ?, CASE WHEN (${query}) THEN 1 ELSE 0 END`,id,...args);}

export async function shopSnapshot(request?:Request){
 const user=await identity(request);
 const productRows=await all<{code:string;name:string;protocol:string;price:number;enabled:number;kind:string;description:string;seller_id:string|null;review_state:string}>("SELECT * FROM products ORDER BY CASE WHEN kind='PROXY' THEN 0 ELSE 1 END,name");
 const products=[...plans.filter(p=>!productRows.some(r=>r.code===p.code)).map(p=>({...p,price:0,enabled:false,kind:"PROXY",description:""})),...productRows.filter(p=>!p.seller_id||p.review_state==="APPROVED"||user?.isAdmin||p.seller_id===user?.userId).map(p=>({...p,enabled:!!p.enabled}))];
 const paymentInstructions=(await sql("SELECT value FROM shop_settings WHERE key='payment_instructions'").first<{value:string}>())?.value??"";
 if(!user)return {products,paymentInstructions,user:null};await register(user);
 const proxies=await all("SELECT s.id,s.position,s.order_id,s.expires,p.host,p.port,p.protocol,p.region,p.health,p.checked,p.latency,p.last_error FROM slots s JOIN stock p ON p.id=s.stock_id JOIN orders o ON o.id=s.order_id WHERE o.customer_id=? ORDER BY s.created,s.position",user.userId);
 const orders=await all("SELECT o.*,c.email customer_email,p.name product_name FROM orders o JOIN customers c ON c.id=o.customer_id JOIN products p ON p.code=o.product "+(user.isAdmin?"":"WHERE o.customer_id=? ")+"ORDER BY o.created DESC LIMIT 200",...user.isAdmin?[]:[user.userId]);
 const history=await all("SELECT w.id,w.created,w.reason,s.position,s.expires,o.id order_id,a.host old_host,a.port old_port,b.host new_host,b.port new_port,c.email customer_email FROM warranty w JOIN slots s ON s.id=w.slot_id JOIN orders o ON o.id=s.order_id JOIN customers c ON c.id=o.customer_id JOIN stock a ON a.id=w.old_stock JOIN stock b ON b.id=w.new_stock "+(user.isAdmin?"":"WHERE o.customer_id=? ")+"ORDER BY w.created DESC LIMIT 200",...user.isAdmin?[]:[user.userId]);
 const notifications=await all("SELECT id,message,created FROM notifications WHERE customer_id=? ORDER BY created DESC LIMIT 30",user.userId);
 const inventory=user.isAdmin?await all("SELECT id,host,port,protocol,region,state,health,failures,checked,latency,last_error,provider_expiry,archived FROM stock ORDER BY created DESC LIMIT 1000"):[];
 const runs=user.isAdmin?await all("SELECT * FROM runs ORDER BY created DESC LIMIT 10"):[];
 const sellerData=await sellerSnapshot(database(),user);return {...await promotionSnapshot(database(),user.isAdmin),...sellerData,...await walletSnapshot(database(),user.userId,user.isAdmin),...await digitalSnapshot(database(),user.userId,user.isAdmin),products,paymentInstructions,user:{email:user.email,name:user.displayName,isAdmin:user.isAdmin,isSeller:!!sellerData.seller.membership?.active,authMethod:user.authMethod},proxies,orders,history,notifications,inventory,runs};
}

export async function shopAction(request:Request,payload:Record<string,unknown>){
 const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new ShopError("Yêu cầu khác nguồn bị từ chối.",403);
 const user=await identity(request);if(!user)throw new ShopError("Vui lòng đăng nhập trước.",401);await register(user);
 const action=payload.action;if(["coupon-quote","coupon-publish","coupon-toggle","announcement-publish","announcement-toggle"].includes(String(action)))return locked(async()=>promotionAction(database(),user,payload));if(action==="archive-stock"){if(!user.isAdmin)throw new ShopError("Chỉ quản trị viên được thao tác.",403);if(typeof payload.archived!=="boolean")throw new ShopError("Trạng thái kho không hợp lệ.");return locked(async()=>{await sql("UPDATE stock SET archived=? WHERE id=?",payload.archived?1:0,String(payload.id)).run();return {message:payload.archived?"Đã ẩn dòng khỏi kho. Dữ liệu của khách được giữ nguyên.":"Đã khôi phục dòng trong kho."};});}if(String(action).startsWith("seller-"))return locked(async()=>sellerAction(database(),secret(),user,payload));const adminActions=["import","settings","approve","edit","maintenance","save-product","import-items","sepay-settings","sepay-banks"];
 if(adminActions.includes(String(action))&&!user.isAdmin)throw new ShopError("Chỉ quản trị viên được thao tác.",403);
 if(["sepay-settings","sepay-banks","create-topup","check-topup"].includes(String(action)))return walletAction(database(),secret(),user.userId,payload);
 if(action==="wallet-order")return locked(async assert=>{
  const count=quantity(payload.quantity),requestId=String(payload.requestId);if(!/^[a-f0-9-]{36}$/.test(requestId))throw new ShopError("Mã yêu cầu không hợp lệ.");
  let order=await sql("SELECT * FROM orders WHERE customer_id=? AND request_id=?",user.userId,requestId).first<Order>();
  if(order){if(order.payment_method!=="WALLET"||order.product!==payload.product||order.quantity!==count||order.coupon_code!==couponCode(payload.coupon))throw new ShopError("Mã yêu cầu đã dùng cho đơn khác.",409);if(order.status==="APPROVED")return {message:"Đơn đã được giao, không trừ tiền lại.",orderId:order.id,delivered:true};if(order.status!=="PENDING")throw new ShopError("Đơn không còn chờ xử lý.",409);}
  else{const product=await sql("SELECT code,price,seller_id FROM products WHERE code=? AND enabled=1 AND (seller_id IS NULL OR review_state='APPROVED')",String(payload.product)).first<{code:string;price:number;seller_id:string|null}>();if(!product||product.price<=0)throw new ShopError("Sản phẩm chưa mở bán.");const quote=await couponQuote(database(),user.userId,product,count,payload.coupon),total=quote.total;if(await walletBalance(database(),user.userId)<total)throw new ShopError("Số dư chưa đủ. Hãy nạp tiền trước.",409);const pending=await sql("SELECT COUNT(*) n FROM orders WHERE customer_id=? AND status='PENDING'",user.userId).first<{n:number}>();if((pending?.n??0)>=10)throw new ShopError("Bạn đang có 10 đơn chờ. Hãy xử lý trước.");const id=crypto.randomUUID();await database().batch([sql("INSERT INTO orders(id,customer_id,product,quantity,unit_price,total,created,request_id,seller_id,unit_fee,payment_method,coupon_code,discount) VALUES(?,?,?,?,?,?,?,?,?,?,'WALLET',?,?)",id,user.userId,product.code,count,product.price,total,Date.now(),requestId,product.seller_id,product.seller_id?sellerFee(product.price):0,quote.code,quote.discount),...couponReservation(database(),id,user.userId,quote.code)]);order=await sql("SELECT * FROM orders WHERE id=?",id).first<Order>();}
  if(!order)throw new ShopError("Không tìm thấy đơn.");if(await walletBalance(database(),user.userId)<order.total)throw new ShopError("Số dư chưa đủ. Chưa trừ tiền.",409);
  const result=await fulfil(order,assert,walletDebit(database(),order));return {...result,orderId:order.id,delivered:true};
 });
 if(["save-product","import-items","export-items"].includes(String(action)))return digitalAction(database(),secret(),user.userId,payload);
 if(action==="settings"){
  const input=payload.products;if(!Array.isArray(input)||input.length!==2)throw new ShopError("Cần cấu hình hai gói HTTP và SOCKS5.");
  const instructions=typeof payload.paymentInstructions==='string'?payload.paymentInstructions.trim():"";if(instructions.length>3000||(input.some(p=>p?.enabled)&&instructions.length<10))throw new ShopError("Nhập hướng dẫn thanh toán (10–3.000 ký tự) trước khi mở bán.");
  const statements=plans.map(p=>{const setting=input.find(x=>x?.code===p.code);if(!setting||!Number.isInteger(setting.price)||setting.price<0||setting.price>10000000||typeof setting.enabled!=="boolean"||(setting.enabled&&setting.price===0))throw new ShopError("Giá bán phải là số nguyên dương khi mở bán.");return sql("INSERT INTO products(code,name,protocol,price,enabled) VALUES(?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET price=excluded.price,enabled=excluded.enabled",p.code,p.name,p.protocol,setting.price,setting.enabled?1:0);});statements.push(sql("INSERT INTO shop_settings(key,value) VALUES('payment_instructions',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",instructions));await database().batch(statements);return {message:"Đã lưu giá, thanh toán và trạng thái mở bán."};
 }
 if(action==="import"){
  const protocol=payload.protocol;if(protocol!=="HTTP"&&protocol!=="SOCKS5")throw new ShopError("Chọn HTTP hoặc SOCKS5.");const region=typeof payload.region==="string"?payload.region.trim().slice(0,60):"Việt Nam";
  const providerExpiry=payload.providerExpiry==null?null:Number(payload.providerExpiry);if(providerExpiry!==null&&(!Number.isSafeInteger(providerExpiry)||providerExpiry<=Date.now()))throw new ShopError("Hạn proxy phải nằm trong tương lai.");
  const rows=parseProxyLines(payload.text);const statements=[];for(const p of rows){statements.push(sql("INSERT INTO stock(id,fingerprint,host,port,protocol,region,credentials,created,provider_expiry) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(fingerprint) DO NOTHING",crypto.randomUUID(),await fingerprint(p.host,p.port,protocol,p.user),p.host,p.port,protocol,region,await encryptCredentials(p,secret()),Date.now(),providerExpiry));}let inserted=0;for(let i=0;i<statements.length;i+=50){const result=await database().batch(statements.slice(i,i+50));inserted+=result.reduce((n,r)=>n+r.meta.changes,0);}return {message:`Đã nhập ${inserted} proxy; bỏ qua ${rows.length-inserted} dòng trùng. Proxy mới đang chờ kiểm tra.`};
 }
 if(action==="create-order")return locked(async()=>{
  const count=quantity(payload.quantity);if(typeof payload.requestId!=="string"||!/^[a-f0-9-]{36}$/.test(payload.requestId))throw new ShopError("Mã yêu cầu không hợp lệ.");
  const existing=await sql("SELECT * FROM orders WHERE customer_id=? AND request_id=?",user.userId,payload.requestId).first<Order>();if(existing){if(existing.payment_method!=="MANUAL"||existing.product!==payload.product||existing.quantity!==count||existing.coupon_code!==couponCode(payload.coupon))throw new ShopError("Mã yêu cầu đã dùng cho đơn khác.",409);return {orderId:existing.id,message:`Đơn đã được tạo. Nội dung chuyển khoản: PH${existing.id.slice(0,8).toUpperCase()}.`};}
  const product=await sql("SELECT * FROM products WHERE code=? AND enabled=1 AND (seller_id IS NULL OR review_state='APPROVED')",String(payload.product)).first<{code:string;price:number;seller_id:string|null}>();if(!product||product.price<=0)throw new ShopError("Gói này chưa mở bán.");
  const pending=await sql("SELECT COUNT(*) count FROM orders WHERE customer_id=? AND status='PENDING'",user.userId).first<{count:number}>();if((pending?.count??0)>=10)throw new ShopError("Bạn đang có 10 đơn chờ. Hãy xử lý hoặc hủy trước khi tạo thêm.");
  const quote=await couponQuote(database(),user.userId,product,count,payload.coupon);const id=crypto.randomUUID();await database().batch([sql("INSERT INTO orders(id,customer_id,product,quantity,unit_price,total,created,request_id,seller_id,unit_fee,coupon_code,discount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(customer_id,request_id) DO NOTHING",id,user.userId,product.code,count,product.price,quote.total,Date.now(),payload.requestId,product.seller_id,product.seller_id?sellerFee(product.price):0,quote.code,quote.discount),...couponReservation(database(),id,user.userId,quote.code)]);const saved=await sql("SELECT id FROM orders WHERE customer_id=? AND request_id=?",user.userId,payload.requestId).first<{id:string}>();return {orderId:saved?.id,message:`Đơn chờ xác nhận. Nội dung chuyển khoản: PH${saved?.id.slice(0,8).toUpperCase()}.`};
 });
 if(action==="cancel"){
  const result=await sql("UPDATE orders SET status='CANCELLED' WHERE id=? AND status='PENDING'"+(user.isAdmin?"":" AND customer_id=?"),String(payload.id),...user.isAdmin?[]:[user.userId]).run();if(!result.meta.changes)throw new ShopError("Không thể hủy đơn này.",409);return {message:"Đã hủy đơn."};
 }
 if(action==="approve")return locked(async assert=>{
  const order=await sql("SELECT * FROM orders WHERE id=?",String(payload.id)).first<Order>();if(!order||order.status!=="PENDING")throw new ShopError("Đơn không còn ở trạng thái chờ.",409);
  if(order.payment_method==="WALLET")throw new ShopError("Đơn ví phải do người mua thanh toán bằng số dư; không duyệt tay.",409);
  return fulfil(order,assert);
 });
 if(action==="export"){
  if(!Array.isArray(payload.ids)||payload.ids.length>1000||payload.ids.some(x=>typeof x!=="string"))throw new ShopError("Danh sách dòng không hợp lệ.");const records=await all<{id:string;host:string;port:number;credentials:string}>("SELECT s.id,p.host,p.port,p.credentials FROM slots s JOIN stock p ON p.id=s.stock_id JOIN orders o ON o.id=s.order_id WHERE o.customer_id=? AND s.expires>? ORDER BY s.created,s.position",user.userId,Date.now());const chosen=payload.ids.length?records.filter(p=>(payload.ids as string[]).includes(p.id)):records;if(!chosen.length)throw new ShopError("Không có proxy còn hạn để xuất.");const lines=[];for(const p of chosen){const c=await decryptCredentials(p.credentials,secret());lines.push(`${p.host}:${p.port}:${c.user}:${c.password}`);}return {text:lines.join("\n"),message:`Đã xuất ${lines.length} proxy còn hạn.`};
 }
 if(action==="edit")return locked(async assert=>{
  const item=await sql("SELECT * FROM stock WHERE id=?",String(payload.id)).first<Stock>();if(!item)throw new ShopError("Không tìm thấy proxy.",404);if(typeof payload.region!=="string"||payload.region.length>60)throw new ShopError("Vị trí tối đa 60 ký tự.");
  let credentials=item.credentials;let newFingerprint:string|null=null;if(typeof payload.user==="string"&&typeof payload.password==="string"&&payload.user&&payload.password){const p=parseProxyLines(`${item.host}:${item.port}:${payload.user}:${payload.password}`)[0];credentials=await encryptCredentials(p,secret());newFingerprint=await fingerprint(p.host,p.port,item.protocol,p.user);}
  const expiry=payload.providerExpiry==null?null:Number(payload.providerExpiry);if(expiry!==null&&(!Number.isSafeInteger(expiry)||expiry<Date.now()))throw new ShopError("Hạn proxy không hợp lệ.");await assert();await sql("UPDATE stock SET region=?,fingerprint=COALESCE(?,fingerprint),health=CASE WHEN credentials<>? THEN 'UNKNOWN' ELSE health END,checked=CASE WHEN credentials<>? THEN 0 ELSE checked END,failures=CASE WHEN credentials<>? THEN 0 ELSE failures END,credentials=?,provider_expiry=? WHERE id=?",payload.region.trim(),newFingerprint,credentials,credentials,credentials,credentials,expiry,item.id).run();return {message:"Đã cập nhật proxy. Hạn bảo hành của khách được giữ nguyên."};
 });
 if(action==="maintenance")return maintenance();
 throw new ShopError("Thao tác không được hỗ trợ.");
}

export async function maintenance(){return locked(async assert=>{
 await baseline();let checked=0,replaced=0;const now=Date.now();
 const pool=await all<Stock>("SELECT p.* FROM stock p LEFT JOIN slots s ON s.stock_id=p.id WHERE p.checked<=? AND ((p.state='ASSIGNED' AND s.expires>?) OR (p.state='AVAILABLE' AND p.archived=0 AND (p.provider_expiry IS NULL OR p.provider_expiry>?))) AND p.health<>'BLOCKED' ORDER BY CASE WHEN p.state='ASSIGNED' THEN 0 ELSE 1 END,p.checked LIMIT 20",now-MIN_CHECK_INTERVAL,now,now);
 for(let i=0;i<pool.length;i+=4){await assert();await Promise.all(pool.slice(i,i+4).map(p=>probe(p)));checked+=pool.slice(i,i+4).length;}
 const broken=await all<{id:string;stock_id:string;expires:number;position:number;customer_id:string;protocol:string;failures:number;product:string|null}>("SELECT s.*,o.customer_id,p.protocol,p.failures,p.product FROM slots s JOIN orders o ON o.id=s.order_id JOIN stock p ON p.id=s.stock_id WHERE p.health='DEAD' AND p.failures>=3 AND s.expires>? ORDER BY s.expires LIMIT 5",Date.now());
 for(const slot of broken){if(!canReplace(slot.failures,slot.expires,Date.now()))continue;await assert();const healthy=await verified(await candidates(slot.protocol,slot.expires,4,slot.product),1);const candidate=healthy[0];if(!candidate){await sql("INSERT INTO notifications(id,customer_id,message,created,dedupe) VALUES(?,?,?,?,?) ON CONFLICT(dedupe) DO NOTHING",crypto.randomUUID(),slot.customer_id,`Proxy dòng ${slot.position} đã lỗi 3 lần. Kho dự phòng cùng loại chưa có proxy live; hệ thống sẽ thử lại.`,Date.now(),`missing:${slot.id}:${slot.stock_id}`).run();continue;}await assert();
  const guard=crypto.randomUUID();await database().batch([transactionGuard(guard,"(SELECT stock_id FROM slots WHERE id=?)=? AND (SELECT expires FROM slots WHERE id=?)>? AND (SELECT state FROM stock WHERE id=?)='AVAILABLE'",slot.id,slot.stock_id,slot.id,Date.now(),candidate.id),sql("UPDATE slots SET stock_id=? WHERE id=?",candidate.id,slot.id),sql("UPDATE stock SET state='ASSIGNED' WHERE id=?",candidate.id),sql("UPDATE stock SET state='QUARANTINED' WHERE id=?",slot.stock_id),sql("INSERT INTO warranty(id,slot_id,old_stock,new_stock,reason,created) VALUES(?,?,?,?,?,?)",crypto.randomUUID(),slot.id,slot.stock_id,candidate.id,"3 lần kiểm tra lỗi liên tiếp, cách nhau ít nhất 5 phút",Date.now()),sql("INSERT INTO notifications(id,customer_id,message,created,dedupe) VALUES(?,?,?,?,?)",crypto.randomUUID(),slot.customer_id,`Đã thay proxy dòng ${slot.position}, giữ nguyên hạn dùng. Hãy tải lại TXT để lấy proxy mới.`,Date.now(),`replaced:${slot.id}:${slot.stock_id}`),sql("DELETE FROM transaction_guards WHERE id=?",guard)]);replaced++;
 }
 await assert();await sql("UPDATE stock SET state='EXPIRED' WHERE state='ASSIGNED' AND id IN (SELECT stock_id FROM slots WHERE expires<=?)",Date.now()).run();await sql("INSERT INTO runs(id,created,checked,replaced,message) VALUES(?,?,?,?,?)",crypto.randomUUID(),Date.now(),checked,replaced,"Hoàn tất kiểm tra; giữ nguyên hạn bảo hành khi thay proxy.").run();await sql("DELETE FROM runs WHERE created<?",Date.now()-7*86400000).run();return {message:`Đã kiểm tra ${checked} proxy, thay thế ${replaced} proxy.`,checked,replaced};
});}

export function shopFailure(error:unknown){if(error instanceof ShopError)return Response.json({error:error.message},{status:error.status,headers:{"Cache-Control":"no-store"}});console.error("Shop operation failed",error instanceof Error?error.name:"unknown");return Response.json({error:"Không thể xử lý lúc này. Dữ liệu đã được giữ lại; vui lòng thử lại."},{status:503,headers:{"Cache-Control":"no-store"}});}

async function fulfil(order:Order,assert:()=>Promise<void>,extra:D1PreparedStatement[]=[]){
  if(order.seller_id&&!(await sql("SELECT active FROM sellers WHERE customer_id=?",order.seller_id).first<{active:number}>())?.active)throw new ShopError("CTV đang bị khóa. Chưa giao hàng hoặc trừ tiền.",409);extra=[...extra,...saleStatements(database(),order)];
  const product=await sql("SELECT protocol,kind,seller_id FROM products WHERE code=?",order.product).first<{protocol:string;kind:string;seller_id:string|null}>();if(!product)throw new ShopError("Không tìm thấy gói.");if(product.kind!=="PROXY")return approveDigital(database(),order,assert,extra);await baseline();
  const expires=Date.now()+WARRANTY_MS;const pool=await candidates(product.protocol,expires,Math.min(40,order.quantity+8),product.seller_id?order.product:null);const healthy=await verified(pool,order.quantity);if(healthy.length<order.quantity)throw new ShopError(`Kho chỉ có ${healthy.length} proxy đã xác nhận live, chưa đủ ${order.quantity}. Đơn vẫn chờ.`,409);await assert();
  const guard=crypto.randomUUID();const statements=[...extra,transactionGuard(guard,"(SELECT status FROM orders WHERE id=?)='PENDING' AND (SELECT COUNT(*) FROM stock WHERE id IN ("+healthy.map(()=>"?").join(",")+") AND state='AVAILABLE')=?",order.id,...healthy.map(p=>p.id),order.quantity)];
  healthy.forEach((p,i)=>{statements.push(sql("INSERT INTO slots(id,order_id,position,stock_id,expires,created) VALUES(?,?,?,?,?,?)",crypto.randomUUID(),order.id,i+1,p.id,expires,Date.now()));statements.push(sql("UPDATE stock SET state='ASSIGNED' WHERE id=?",p.id));});statements.push(sql("UPDATE orders SET status='APPROVED',approved=? WHERE id=?",Date.now(),order.id));statements.push(sql("INSERT INTO notifications(id,customer_id,message,created,dedupe) VALUES(?,?,?,?,?)",crypto.randomUUID(),order.customer_id,`Đơn ${order.id.slice(0,8)} đã được cấp ${order.quantity} proxy. Bảo hành 30 ngày bắt đầu từ lúc cấp.`,Date.now(),`approved:${order.id}`));statements.push(sql("DELETE FROM transaction_guards WHERE id=?",guard));await database().batch(statements);return {message:`Đã cấp ${order.quantity} proxy đã kiểm tra live; bảo hành 30 ngày.`};
}

export async function scheduledMaintenance(){let payments:{credited:number;reviewed:number}|undefined,paymentError:unknown;try{payments=await syncSePay(database(),secret());}catch(e){paymentError=e;}const result=await maintenance();if(paymentError)throw new ShopError("Đã kiểm tra proxy; đối soát SePay lỗi: "+(paymentError instanceof ShopError?paymentError.message:"Kiểm tra cấu hình ngân hàng."),503);return {...result,payments};}

