import {sqliteTable,text,integer,uniqueIndex,check,index} from "drizzle-orm/sqlite-core";
import {sql} from "drizzle-orm";
export const products=sqliteTable("products",{code:text("code").primaryKey(),name:text("name").notNull(),protocol:text("protocol").notNull(),price:integer("price").notNull(),enabled:integer("enabled").notNull().default(0),kind:text("kind").notNull().default("PROXY"),description:text("description").notNull().default(""),sellerId:text("seller_id"),reviewState:text("review_state").notNull().default("APPROVED"),reviewNote:text("review_note").notNull().default("")});
export const authAccounts=sqliteTable("auth_accounts",{customerId:text("customer_id").primaryKey().references(()=>customers.id),email:text("email").notNull(),salt:text("salt").notNull(),passwordHash:text("password_hash").notNull(),role:text("role").notNull().default("CUSTOMER")},t=>[uniqueIndex("auth_email").on(t.email)]);
export const authSessions=sqliteTable("auth_sessions",{tokenHash:text("token_hash").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id),expires:integer("expires").notNull()});
export const authLimits=sqliteTable("auth_limits",{id:text("id").primaryKey(),count:integer("count").notNull(),expires:integer("expires").notNull()});
export const sellers=sqliteTable("sellers",{customerId:text("customer_id").primaryKey().references(()=>customers.id),role:text("role").notNull().default("SELLER"),active:integer("active").notNull().default(1),created:integer("created").notNull()});
export const sellerInvites=sqliteTable("seller_invites",{tokenHash:text("token_hash").primaryKey(),email:text("email").notNull(),expires:integer("expires").notNull(),usedBy:text("used_by"),created:integer("created").notNull()});
export const sellerSales=sqliteTable("seller_sales",{orderId:text("order_id").primaryKey().references(()=>orders.id),sellerId:text("seller_id").notNull().references(()=>customers.id),quantity:integer("quantity").notNull(),unitPrice:integer("unit_price").notNull(),gross:integer("gross").notNull(),fee:integer("fee").notNull(),net:integer("net").notNull(),created:integer("created").notNull()});
export const digitalStock=sqliteTable("digital_stock",{id:text("id").primaryKey(),product:text("product").notNull().references(()=>products.code),fingerprint:text("fingerprint").notNull(),content:text("content").notNull(),state:text("state").notNull().default("AVAILABLE"),created:integer("created").notNull()},t=>[uniqueIndex("digital_fingerprint").on(t.product,t.fingerprint),index("digital_available").on(t.product,t.state)]);
export const deliveries=sqliteTable("deliveries",{id:text("id").primaryKey(),orderId:text("order_id").notNull().references(()=>orders.id),stockId:text("stock_id").notNull().references(()=>digitalStock.id),position:integer("position").notNull(),created:integer("created").notNull()},t=>[uniqueIndex("delivery_stock").on(t.stockId),uniqueIndex("delivery_position").on(t.orderId,t.position)]);
export const shopSettings=sqliteTable("shop_settings",{key:text("key").primaryKey(),value:text("value").notNull()});
export const topups=sqliteTable("topups",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id),code:text("code").notNull(),amount:integer("amount").notNull(),status:text("status").notNull().default("PENDING"),bankId:text("bank_id").notNull(),accountNumber:text("account_number").notNull(),created:integer("created").notNull(),expires:integer("expires").notNull(),checked:integer("checked").notNull().default(0),credited:integer("credited"),transactionId:text("transaction_id"),requestId:text("request_id").notNull(),note:text("note").notNull().default("")},t=>[uniqueIndex("topup_code").on(t.code),uniqueIndex("topup_transaction").on(t.transactionId),uniqueIndex("topup_request").on(t.customerId,t.requestId)]);
export const walletEntries=sqliteTable("wallet_entries",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id),amount:integer("amount").notNull(),kind:text("kind").notNull(),reference:text("reference").notNull(),created:integer("created").notNull()},t=>[uniqueIndex("wallet_reference").on(t.reference),index("wallet_customer").on(t.customerId,t.created)]);
export const customers=sqliteTable("customers",{id:text("id").primaryKey(),email:text("email").notNull(),name:text("name").notNull(),created:integer("created").notNull()});
export const stock=sqliteTable("stock",{id:text("id").primaryKey(),fingerprint:text("fingerprint").notNull(),host:text("host").notNull(),port:integer("port").notNull(),protocol:text("protocol").notNull(),region:text("region").notNull(),credentials:text("credentials").notNull(),archived:integer("archived").notNull().default(0),state:text("state").notNull().default("AVAILABLE"),health:text("health").notNull().default("UNKNOWN"),failures:integer("failures").notNull().default(0),checked:integer("checked").notNull().default(0),latency:integer("latency"),lastError:text("last_error"),providerExpiry:integer("provider_expiry"),product:text("product").references(()=>products.code),created:integer("created").notNull()},t=>[uniqueIndex("stock_fingerprint").on(t.fingerprint),index("stock_due").on(t.state,t.checked)]);
export const orders=sqliteTable("orders",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id),product:text("product").notNull().references(()=>products.code),quantity:integer("quantity").notNull(),unitPrice:integer("unit_price").notNull(),couponCode:text("coupon_code").notNull().default(""),discount:integer("discount").notNull().default(0),total:integer("total").notNull(),status:text("status").notNull().default("PENDING"),paymentMethod:text("payment_method").notNull().default("MANUAL"),sellerId:text("seller_id"),unitFee:integer("unit_fee").notNull().default(0),created:integer("created").notNull(),approved:integer("approved"),requestId:text("request_id").notNull()},t=>[uniqueIndex("orders_request").on(t.customerId,t.requestId)]);
export const slots=sqliteTable("slots",{id:text("id").primaryKey(),orderId:text("order_id").notNull().references(()=>orders.id),position:integer("position").notNull(),stockId:text("stock_id").notNull().references(()=>stock.id),expires:integer("expires").notNull(),created:integer("created").notNull()},t=>[uniqueIndex("slot_order_position").on(t.orderId,t.position),uniqueIndex("slot_stock").on(t.stockId)]);
export const warranty=sqliteTable("warranty",{id:text("id").primaryKey(),slotId:text("slot_id").notNull().references(()=>slots.id),oldStock:text("old_stock").notNull().references(()=>stock.id),newStock:text("new_stock").notNull().references(()=>stock.id),reason:text("reason").notNull(),created:integer("created").notNull()});
export const notifications=sqliteTable("notifications",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id),message:text("message").notNull(),created:integer("created").notNull(),dedupe:text("dedupe").notNull()},t=>[uniqueIndex("notifications_dedupe").on(t.dedupe)]);
export const runs=sqliteTable("runs",{id:text("id").primaryKey(),created:integer("created").notNull(),checked:integer("checked").notNull(),replaced:integer("replaced").notNull(),message:text("message").notNull()});
export const locks=sqliteTable("locks",{id:text("id").primaryKey(),owner:text("owner").notNull(),expires:integer("expires").notNull()});
// A false precondition aborts the whole D1 batch; successful guard rows are removed in that same batch.
export const guards=sqliteTable("transaction_guards",{id:text("id").primaryKey(),valid:integer("valid").notNull()},t=>[check("valid_transaction",sql`${t.valid} = 1`)]);

export const announcements=sqliteTable("announcements",{id:text("id").primaryKey(),title:text("title").notNull(),message:text("message").notNull(),active:integer("active").notNull().default(1),created:integer("created").notNull()});
export const coupons=sqliteTable("coupons",{code:text("code").primaryKey(),kind:text("kind").notNull(),value:integer("value").notNull(),minTotal:integer("min_total").notNull().default(0),maxDiscount:integer("max_discount").notNull().default(0),product:text("product"),expires:integer("expires").notNull(),maxUses:integer("max_uses").notNull(),enabled:integer("enabled").notNull().default(1),created:integer("created").notNull()});
export const couponUses=sqliteTable("coupon_uses",{orderId:text("order_id").primaryKey().references(()=>orders.id),code:text("code").notNull().references(()=>coupons.code),customerId:text("customer_id").notNull().references(()=>customers.id),created:integer("created").notNull()});

